import socket
import logging
from typing import Optional
from urllib.parse import urlparse

import requests
from rich.table import Table

from .utils import console, log, now_utc, stealth_headers, get_proxy_dict

BLOCK_CODES = {403, 406, 429, 503}

# ─── WAF / Bot-protection signatures ─────────────────────────────────────────
# Covers DataDome and CrowdSec (primary targets) plus all major vendors.

WAF_SIGNATURES = {
    # ── Primary targets ──────────────────────────────────────────────────────
    "DataDome": {
        "headers":  ["x-datadome", "x-datadome-cid", "x-dd-b", "x-dd-s", "x-datadome-isbot"],
        "body_kw":  ["datadome", "dd_referrer", "datadome.co", "_dd_s", "ddcaptcha"],
        "server":   [],
        "cookies":  ["datadome"],
        "notes":    "JS challenge + device fingerprinting. Blocking mode returns 403 with JS page.",
    },
    "CrowdSec": {
        "headers":  ["x-crowdsec", "x-crowdsec-action", "crowdsec-remediation"],
        "body_kw":  ["crowdsec", "crowdsecurity", "crowdsec.net", "crowdsec_ban"],
        "server":   [],
        "cookies":  [],
        "notes":    "Community-sourced IP reputation. Captcha or ban depending on scenario.",
    },
    # ── Major commercial vendors ──────────────────────────────────────────────
    "Cloudflare": {
        "headers":  ["cf-ray", "cf-cache-status", "cf-mitigated", "cf-edge-cache"],
        "body_kw":  ["cloudflare", "ray id", "__cf_bm", "cf-browser-verification", "attention required"],
        "server":   ["cloudflare"],
        "cookies":  ["__cf_bm", "cf_clearance"],
        "notes":    "Broad WAF + bot management. cf-ray present on every response.",
    },
    "PerimeterX": {
        "headers":  ["x-px-block-score", "x-px-uuid", "x-px-vid"],
        "body_kw":  ["perimeterx", "_pxvid", "px-captcha", "pxchallenge", "px.gif"],
        "server":   [],
        "cookies":  ["_px", "_pxvid", "pxcts", "_pxhd"],
        "notes":    "Widely used in e-commerce (Shopify, Magento). Behaviour-based.",
    },
    "Akamai Bot Manager": {
        "headers":  ["x-check-cacheable", "akamai-origin-hop", "x-akamai-transformed",
                     "x-akamai-request-id", "akamai-edge-log-uuid"],
        "body_kw":  ["akamai", "reference #", "akamai ghost", "access denied by akamai"],
        "server":   [],
        "cookies":  ["ak_bmsc", "bm_sz", "bm_sv"],
        "notes":    "Enterprise CDN + WAF. bm_sz cookie indicates Bot Manager active.",
    },
    "AWS WAF": {
        "headers":  ["x-amzn-waf-action", "x-amzn-requestid", "x-amz-apigw-id"],
        "body_kw":  ["aws waf", "request blocked", "awswaf", "403 forbidden"],
        "server":   [],
        "cookies":  ["aws-waf-token"],
        "notes":    "Common on AWS-hosted shops. aws-waf-token cookie for CAPTCHA challenges.",
    },
    "Imperva / Incapsula": {
        "headers":  ["x-iinfo", "x-cdn", "incap-ses", "x-sinadf"],
        "body_kw":  ["imperva", "incapsula", "request unsuccessful", "incap_ses",
                     "powered by incapsula"],
        "server":   [],
        "cookies":  ["incap_ses", "visid_incap", "nlbi_"],
        "notes":    "Often seen on financial/retail. incap_ses cookie is a strong indicator.",
    },
    "F5 BIG-IP ASM": {
        "headers":  ["x-wa-info", "x-cnection"],
        "body_kw":  ["the requested url was rejected", "f5 networks", "support id",
                     "please consult with your administrator"],
        "server":   ["big-ip"],
        "cookies":  ["TS01", "ts01"],
        "notes":    "Enterprise on-premise WAF. 'Support ID' in block page is definitive.",
    },
    "ModSecurity": {
        "headers":  [],
        "body_kw":  ["mod_security", "modsecurity", "not acceptable",
                     "406 not acceptable", "this error was generated by mod_security"],
        "server":   ["apache", "nginx"],
        "cookies":  [],
        "notes":    "Open-source WAF, often on Apache/Nginx. No distinctive headers.",
    },
    "Sucuri": {
        "headers":  ["x-sucuri-id", "x-sucuri-cache"],
        "body_kw":  ["sucuri", "sucuri website firewall", "access denied | sucuri"],
        "server":   ["sucuri"],
        "cookies":  [],
        "notes":    "Popular with WordPress shops. x-sucuri-id on every response.",
    },
    "Radware AppWall": {
        "headers":  ["x-rdwr-pop", "x-sl-compstate"],
        "body_kw":  ["radware", "appwall", "the requested url was blocked by radware"],
        "server":   [],
        "cookies":  [],
        "notes":    "Enterprise MSSP WAF. Uncommon in e-commerce.",
    },
    "Reblaze": {
        "headers":  ["x-reblaze-protection", "rbzid"],
        "body_kw":  ["reblaze", "this request has been blocked by reblaze"],
        "server":   [],
        "cookies":  ["rbzid"],
        "notes":    "Cloud-native WAF. rbzid session cookie is definitive.",
    },
    "Barracuda WAF": {
        "headers":  ["x-barracuda-link", "x-barracuda-start-time"],
        "body_kw":  ["barracuda", "barracuda networks", "barracuda web application firewall"],
        "server":   [],
        "cookies":  ["barra_counter_session"],
        "notes":    "SMB-focused WAF appliance.",
    },
}

# ─── CDN signatures ───────────────────────────────────────────────────────────

CDN_SIGNATURES = {
    "Cloudflare":    ["cf-ray", "cf-cache-status"],
    "Akamai":        ["x-check-cacheable", "akamai-origin-hop", "x-akamai-transformed"],
    "Fastly":        ["x-fastly-request-id", "fastly-restarts", "x-served-by"],
    "AWS CloudFront": ["x-amz-cf-id", "x-amz-cf-pop"],
    "Azure CDN":     ["x-msedge-ref"],
    "Varnish":       ["x-varnish"],
    "Squid":         ["x-squid-error"],
    "Nginx":         [],   # detected via Server header only
}

# ─── WAF probe payloads ───────────────────────────────────────────────────────

WAF_PROBES = [
    {
        "name": "SQLi Probe",
        "method": "GET",
        "path": "/",
        "headers": {},
        "params": {"id": "1' OR '1'='1"},
        "desc": "Classic SQL injection in query string — should trigger any rule-based WAF",
    },
    {
        "name": "XSS UA Probe",
        "method": "GET",
        "path": "/",
        "headers": {"User-Agent": "<script>alert(1)</script>"},
        "params": {},
        "desc": "XSS payload in User-Agent — tests header inspection depth",
    },
    {
        "name": "Path Traversal",
        "method": "GET",
        "path": "/../../../etc/passwd",
        "headers": {},
        "params": {},
        "desc": "Directory traversal — common WAF signature",
    },
    {
        "name": "XFF Spoof",
        "method": "GET",
        "path": "/",
        "headers": {"X-Forwarded-For": "127.0.0.1"},
        "params": {},
        "desc": "Localhost IP spoofing via XFF — tests IP allow-list bypass",
    },
    {
        "name": "Empty User-Agent",
        "method": "GET",
        "path": "/",
        "headers": {"User-Agent": ""},
        "params": {},
        "desc": "Missing UA is a strong bot signal for DataDome and CrowdSec",
    },
    {
        "name": "Known Bot UA",
        "method": "GET",
        "path": "/",
        "headers": {"User-Agent": "python-requests/2.31.0"},
        "params": {},
        "desc": "Naked requests UA — the most basic bot tell. Both DD and CS block this.",
    },
    {
        "name": "Scanner UA",
        "method": "GET",
        "path": "/wp-admin/",
        "headers": {"User-Agent": "Nikto/2.1.6"},
        "params": {},
        "desc": "Security scanner UA on admin path — double trigger for WAF/bot rules",
    },
    {
        "name": "Header Injection",
        "method": "GET",
        "path": "/",
        "headers": {"X-Custom-IP-Authorization": "127.0.0.1"},
        "params": {},
        "desc": "Custom header injection for internal IP bypass attempt",
    },
]


# ─── Detection helpers ────────────────────────────────────────────────────────

def _detect_waf(responses: list[dict]) -> tuple[str, str]:
    all_headers: dict[str, str] = {}
    all_bodies: str = ""
    all_cookies: str = ""

    for r in responses:
        all_headers.update({k.lower(): v.lower() for k, v in r.get("headers", {}).items()})
        all_bodies += r.get("body", "").lower()
        # Extract Set-Cookie values for cookie-based detection
        for k, v in r.get("headers", {}).items():
            if k.lower() in ("set-cookie", "cookie"):
                all_cookies += v.lower() + " "

    for vendor, sigs in WAF_SIGNATURES.items():
        for h in sigs["headers"]:
            if h.lower() in all_headers:
                return vendor, f"header:{h}"
        for kw in sigs["body_kw"]:
            if kw in all_bodies:
                return vendor, f"body:{kw}"
        server_val = all_headers.get("server", "")
        for s in sigs["server"]:
            if s in server_val:
                return vendor, f"server:{s}"
        for ck in sigs.get("cookies", []):
            if ck.lower() in all_cookies:
                return vendor, f"cookie:{ck}"

    blocked = any(r.get("status") in BLOCK_CODES for r in responses)
    if blocked:
        return "Unknown WAF", "blocked-probe"
    return "None detected", ""


def _detect_cdn(headers: dict) -> str:
    lower = {k.lower(): v for k, v in headers.items()}
    server = lower.get("server", "")
    if "nginx" in server and "cloudflare" not in server:
        pass  # Nginx alone is not a CDN
    for cdn, sig_headers in CDN_SIGNATURES.items():
        for sh in sig_headers:
            if sh.lower() in lower:
                return cdn
    return "None detected"


def _detect_blocking_mode(responses: list[dict]) -> str:
    for r in responses:
        if r.get("status") in BLOCK_CODES:
            return "ACTIVE"
    return "PASSIVE (detection-only)"


# ─── Main entry point ─────────────────────────────────────────────────────────

def run(target_url: str, timeout: int = 10, logger: Optional[logging.Logger] = None) -> dict:
    result: dict = {
        "target_alive": False,
        "waf_detected": "Unknown",
        "waf_match_reason": "",
        "waf_notes": "",
        "blocking_mode": "Unknown",
        "cdn_detected": "Unknown",
        "tech_stack": [],
        "rate_limit_headers": {},
        "robots_txt": False,
        "sitemap_xml": False,
        "https_enforced": target_url.startswith("https://"),
        "hsts": False,
        "probe_results": [],
    }

    parsed = urlparse(target_url)
    hostname = parsed.hostname or ""
    proxies = get_proxy_dict()

    log(f"[PREFLIGHT] Resolving DNS: {hostname}", "info", logger)
    try:
        socket.getaddrinfo(hostname, None)
    except socket.gaierror as e:
        log(f"[PREFLIGHT] DNS resolution failed: {e}", "error", logger)
        return result

    log(f"[PREFLIGHT] Checking target alive: {target_url}", "info", logger)
    try:
        r = requests.head(
            target_url, timeout=timeout, allow_redirects=True,
            headers=stealth_headers(), proxies=proxies,
        )
        result["target_alive"] = True
        base_headers = dict(r.headers)
    except Exception as e:
        log(f"[PREFLIGHT] Target unreachable: {e}", "error", logger)
        return result

    result["cdn_detected"] = _detect_cdn(base_headers)

    server  = base_headers.get("Server", base_headers.get("server", ""))
    powered = base_headers.get("X-Powered-By", base_headers.get("x-powered-by", ""))
    gen     = base_headers.get("X-Generator", base_headers.get("x-generator", ""))
    for val in (server, powered, gen):
        if val and val not in result["tech_stack"]:
            result["tech_stack"].append(val)

    lower_keys = {k.lower() for k in base_headers}
    if "strict-transport-security" in lower_keys:
        result["hsts"] = True
    for rh in ("X-RateLimit-Limit", "Retry-After", "RateLimit-Limit", "RateLimit-Reset"):
        if rh.lower() in lower_keys:
            result["rate_limit_headers"][rh] = base_headers.get(rh, "")

    for path_check, key in (("/robots.txt", "robots_txt"), ("/sitemap.xml", "sitemap_xml")):
        try:
            cr = requests.get(
                target_url.rstrip("/") + path_check, timeout=timeout,
                headers=stealth_headers(), allow_redirects=True, proxies=proxies,
            )
            result[key] = cr.status_code == 200
        except Exception:
            pass

    log("[PREFLIGHT] Running WAF probe requests...", "info", logger)
    probe_results: list[dict] = []

    for probe in WAF_PROBES:
        url = target_url.rstrip("/") + probe["path"]
        hdrs = stealth_headers()
        hdrs.update(probe["headers"])
        try:
            pr = requests.get(
                url, headers=hdrs, params=probe["params"],
                timeout=timeout, allow_redirects=False, proxies=proxies,
            )
            probe_results.append({
                "timestamp":   now_utc(),
                "probe_name":  probe["name"],
                "probe_desc":  probe.get("desc", ""),
                "url":         url,
                "status":      pr.status_code,
                "headers":     dict(pr.headers),
                "body":        pr.text[:2000] if pr.text else "",
                "body_snippet": pr.text[:500] if pr.text else "",
                "error":       None,
            })
            style = "error" if pr.status_code in BLOCK_CODES else "success"
            log(f"  [{probe['name']}] → HTTP {pr.status_code}", style, logger)
        except Exception as e:
            probe_results.append({
                "timestamp":   now_utc(),
                "probe_name":  probe["name"],
                "probe_desc":  probe.get("desc", ""),
                "url":         url,
                "status":      0,
                "headers":     {},
                "body":        "",
                "body_snippet": str(e),
                "error":       str(e),
            })
            log(f"  [{probe['name']}] → ERROR: {e}", "warning", logger)

    result["probe_results"] = probe_results

    waf, waf_reason = _detect_waf(probe_results)
    result["waf_detected"]     = waf
    result["waf_match_reason"] = waf_reason
    result["waf_notes"]        = WAF_SIGNATURES.get(waf, {}).get("notes", "")
    result["blocking_mode"]    = _detect_blocking_mode(probe_results)

    _print_preflight_summary(result)
    return result


def _print_preflight_summary(r: dict) -> None:
    table = Table(
        title="Pre-Flight Security Fingerprint",
        show_header=True, header_style="bold cyan",
    )
    table.add_column("Property",  style="bold white", width=28)
    table.add_column("Value",     style="white")
    table.add_column("Notes",     style="dim",         width=40)

    alive_str = "[bold green]YES[/bold green]" if r["target_alive"] else "[bold red]NO[/bold red]"
    table.add_row("Target Alive", alive_str, "")

    waf   = r["waf_detected"]
    color = "green" if waf == "None detected" else "red"
    reason = f"  ({r['waf_match_reason']})" if r.get("waf_match_reason") else ""
    table.add_row(
        "WAF / Bot Protection",
        f"[{color}]{waf}[/{color}]{reason}",
        r.get("waf_notes", ""),
    )

    mode  = r["blocking_mode"]
    mcolor = "red" if "ACTIVE" in mode else "yellow"
    table.add_row("Blocking Mode", f"[{mcolor}]{mode}[/{mcolor}]", "")

    cdn   = r["cdn_detected"]
    ccolor = "yellow" if cdn != "None detected" else "green"
    table.add_row("CDN", f"[{ccolor}]{cdn}[/{ccolor}]", "")

    table.add_row("Tech Stack",   ", ".join(r["tech_stack"]) or "Unknown", "")
    table.add_row("HTTPS",        "Enforced" if r["https_enforced"] else "Not enforced", "")
    table.add_row("HSTS",         "Present" if r["hsts"] else "Missing", "Add Strict-Transport-Security")
    table.add_row("robots.txt",   "Found" if r["robots_txt"] else "Not found", "")
    table.add_row("sitemap.xml",  "Found" if r["sitemap_xml"] else "Not found", "")
    if r["rate_limit_headers"]:
        table.add_row("Rate-Limit Headers", str(r["rate_limit_headers"]), "")

    console.print(table)
    console.print()
